### PR TITLE
Managed JpegLossless Decoder

### PR DESCRIPTION
**Pull request by gofal**
This code uses a .Net port of a Java library JpegLosslessDecoder. So jpeg lossless encoded image can be decoded with pure managed code in net core project (see #781). Maybe this code also can be used to solve decoding issues for desktop platforms (see #744 and #737).

! This is not a full Codec, since Encoding is not supported ! 

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

### CODE REVIEW

**Comment by PalminX** [comment]
So if I am just interested in JPEG Lossless (JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1])) decoding in .NET Core, will this patch provide it without the need for another package like https://github.com/Efferent-Health/Dicom-native?

**Comment by gofal** [comment]
@PalminX Yes. If you only have fo-dicom core without any other package then you can now decode out of the box jpeg lossless. But you cannot encode and propably it will be slower than the native implementation like the one from efferent-health.
But sometimes native implementation causes problems because it has some dependencies and you have to take care how to compile (explicit x86 or explicit x64, but not AnyCpu), For these scenarios this enhancement will help you.

**Comment by PalminX** [comment]
Thank you very much, this sounds very good... Any ETA when this pull request will go into the development branch?

**Comment by gofal** [comment]
usualy I leave pull requests open for a week or two to give other developers a chance to comment and check. But since this is risk-free and not changing/breaking something, I will merge soon.

**Pull request merged**
