### PR TITLE
Corrected code for check of planar config. in case of YBR_FULL_422 images

### LINKED ISSUE #1049: Possibly incorrect code about getting YBR_ FULL_ 422 image PixelData
Hi! I happened to see this piece of code in [PixelData.cs](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Imaging/Render/PixelData.cs#L171).

``` csharp
...
else if (pi == PhotometricInterpretation.Rgb || pi == PhotometricInterpretation.YbrFull
         || pi == PhotometricInterpretation.YbrFull422 || pi == PhotometricInterpretation.YbrPartial422)
{
    var buffer = pixelData.GetFrame(frame);

    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) buffer = PixelDataConverter.PlanarToInterleaved24(buffer);

    if (pi == PhotometricInterpretation.YbrFull) buffer = PixelDataConverter.YbrFullToRgb(buffer);
    else if (pi == PhotometricInterpretation.YbrFull422) buffer = PixelDataConverter.YbrFull422ToRgb(buffer, pixelData.Width);
    else if (pi == PhotometricInterpretation.YbrPartial422) buffer = PixelDataConverter.YbrPartial422ToRgb(buffer, pixelData.Width);

    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
else if (pi == PhotometricInterpretation.YbrFull422)
{
    var buffer = pixelData.GetFrame(frame);
    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) throw new DicomImagingException("Unsupported planar configuration for YBR_FULL_422");
    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
...
```

There is already exists `pi == PhotometricInterpretation.YbrFull422` in the previous `if` condition, which means that it will never enter the following `if` condition.  
But when **Photometric Interpretation** is **YBR_ FULL_ 422**, Planar Configuration (0028,0006) shall be **0**. Please take a look [here](https://dicom.innolitics.com/ciods/mr-image/image-pixel/00280004).  
Does it mean that the following `if` condition should be correct?  
So, it should looked like this.  
``` csharp
...
else if (pi == PhotometricInterpretation.Rgb || pi == PhotometricInterpretation.YbrFull
         || pi == PhotometricInterpretation.YbrPartial422)
{
    var buffer = pixelData.GetFrame(frame);

    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) buffer = PixelDataConverter.PlanarToInterleaved24(buffer);

    if (pi == PhotometricInterpretation.YbrFull) buffer = PixelDataConverter.YbrFullToRgb(buffer);
    else if (pi == PhotometricInterpretation.YbrPartial422) buffer = PixelDataConverter.YbrPartial422ToRgb(buffer, pixelData.Width);

    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
else if (pi == PhotometricInterpretation.YbrFull422)
{
    if (pixelData.PlanarConfiguration == PlanarConfiguration.Planar) throw new DicomImagingException("Unsupported planar configuration for YBR_FULL_422");
    var buffer = pixelData.GetFrame(frame);
    buffer = PixelDataConverter.YbrFull422ToRgb(buffer, pixelData.Width);
    return new ColorPixelData24(pixelData.Width, pixelData.Height, buffer);
}
...
```

### PR DESCRIPTION
**Pull request by WernMich**
Fixes #1049 

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [X] I have updated the change log
- [X] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
YBR_FULL_422 shall have a planar configuration value of zero, see YBR_FULL_422
YBR_FULL_422 images: check for planar configuration with a value of zero was never done because of matching if-statement with unconditional return statement before

- moved check to first YBR_FULL_422 related if-statement
- replaced confusing if-else statements with if-statements (if-statements always left method scope with return or throw)
- added unit tests

### CODE REVIEW

**Comment by amoerie** [comment]
Hi @WernMich thanks for making this PR! I've requested a review by @gofal, he's the better person for this. 😉

**Comment by amoerie** [comment]
@gofal These changes should also be applied to the v5 source code. 

Do I create a new branch for this or are you already doing it?

**Comment by gofal** [comment]
I am already doing it, thanks

**Comment by gofal** [comment]
so, today I will do the 4.0.6 release and an 5.0.0-alpha2 release.

**Pull request merged**
