### PR TITLE
DICOM.Mono sln update

### PR DESCRIPTION
**Pull request by HelderMPinhal**
Replaced DICOM.Mono for DICOM.Core in the Mono solution
Updated Nuget Packages for the Mono Tools and Examples to beta3
Replaced Internal Dictionaries initialisation on the DICOM Dump tool to allow it to build

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@HelderMPinhal Many thanks for submitting this PR. I am a little concerned though with the changes you have made; it seems like more files than necessary have been affected by your change (*DICOM.Core.csproj*, *MainForm.cs* and *repositories.config*), and it also does not seem correct that the *DICOM.Mono* project has been **removed** from the *DICOM.Core* solution and *C-Store SCP.Mono* and *DICOM Dump.Mono* projects.

With your permission I will take a renewed look at the original issue and try to come up with an alternative, less intrusive, pull request.

**Comment by HelderMPinhal** [comment]
@anders9ustafsson Those aditional changes did not please me as well.
The MainForm.cs change was on purpose so the app could be build. I was getting an error as the method used to load the internal dictionaries didn't exist.

You can go ahead and take a look, of course.
Adding *DICOM.Core* was a quick solution. Another way may be adding the individual files needed to build the solution.

**Comment by anders9ustafsson** [comment]
@HelderMPinhal Thanks. Please have a look at #172, it should provide the "ultimate" solution to this issue.

**Comment by anders9ustafsson** [comment]
Since the issue that this PR is concerned with has been resolved in PR #172, I close this PR now.

**Pull request closed without merging**
