### PR TITLE
Extended IImage interface to clarify ownership. Connected to #144

### PR DESCRIPTION
**Pull request by anders9ustafsson**
Building on @IanYates' invaluable initiative in #145 to improve the ownership control of the `IImage` objects, I have now refactored the implementations of the `IImage` interface to hold the pixel data, thereby having full control over both the underlying image objects *and* the pixel data array.

To facilitate code re-use, I have implemented abstract classes `ImageBase<T>` and `ImageDisposableBase<T>` that implement the `IImage` interface and that are inherited by the different platform image implementations.

I have also introduced a `Clone` method in the `IImage` interface to facilitate and generalize deep copying of `IImage` objects.

Finally, I have continued Ian's work and implemented non-generic extension methods `AsBitmap` etc. for all platforms. I have however removed the `AsBitmapCopy` etc. extension methods; this functionality should instead be covered by the `IImage.Clone` method.

@IanYates many thanks for initiating this important task. Please review, and comment whatever you find questionable or outright wrong.

### CODE REVIEW

**Comment by IanYates** [comment]
Hi - I'll download and run through it tomorrow.  Thanks for finishing this off :)

**Comment by anders9ustafsson** [comment]
@IanYates I cleaned up `ImageGraphic` further; since I have moved `PinnedIntArray` inside the `IImage` implementations there was no longer a motivation for `ImageGraphic` to implement `IDisposable`.

The follow-up question is then, does it make sense for `ImageGraphic`to hold an `IImage` member? Or would it make more sense to skip the member and have `ImageGraphic.RenderImage` always generate a new `IImage` object? Do you see any substantial performance implications with such an approach?

**Comment by anders9ustafsson** [comment]
@IanYates I am going to merge this PR now. I would like to publish a new pre-release on NuGet to get the latest updates thoroughly exposed out in the field. I hope you don't mind that I am not awaiting comments. If you have concerns with this PR, don't hesitate to bring them up though, we can always revert the changes.

Eventually I *did* remove the `IImage` field in `ImageGraphic`, so that now `RenderImage` will *always* return a fresh `IImage` object. As I see it, this should further clarify the ownership, and it should hopefully not be a performance bottleneck in practice, either.

**Comment by IanYates** [comment]
No complaints from me. I'll give it a go early in the week. Been a busy weekend so I haven't had time to catch up on email, GitHub, etc ☺ Thanks for keeping up the momentum!

**Pull request merged**
