### PR TITLE
fix re-add negation sign after recheck

### PR DESCRIPTION
**Pull request by lambacini**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- I think we need to add the negation sign after checking again. In this case we will do the same check with the same value again.

### CODE REVIEW

**Comment by gofal** [comment]
Why do you think, the sign should be added, after the valid number was schecked? Because then acutal the wrong value is checked.
e.g. the check may contain things like checking for a maximum length of the text reprenstaion. if you skip the sign before checking, then the check may pass, but then after adding the sign character, the value may be too big.

Therefore first the decimal string first should be built completely. then the the final result should be validated and checked. Don't you think this is the best approach?

Please provide more information why this change might be necessary/better

**Comment by lambacini** [comment]
I apologize for the inadequate explanation.
Yes, it could be a wrong check for zero-stripping. 
But when checking for a negative value less than -1  in 16byte length, for example -1.123456789012345  (17 characters long with sign)
The ValidateDS function checks the length of the value, in this case it will never validate because we added the negative sign again before the check. 


```c#
public static void ValidateDS(string content)
        {
            // 16 bytes maximum
            if (content.Length > 16)
            {
                throw new DicomValidationException(content, DicomVR.DS, "value exceeds maximum length of 16 characters");
            

```

This may not be the right place to check this, maybe we should do this check in ValidateDS

**Comment by gofal** [comment]
But a decimalstring may in total only be 16 Charakters. That means of course including all characters like
"0"-"9", "+", "-", "E", "e", "."
Where in the Standard did you find that only digit characters are counting and the leading sign may be a 17th character?
 https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html

**Comment by lambacini** [comment]
I think I misunderstood, I'm obviously a little confused. Im sorry to keep you busy.
in this case in decimalstring , negative numbers have 1 less precision than positive numbers, is it true ? 
I examined the dcmtk codes and the same method is used there, it only deletes it when the + value comes, everything else seems to be the same :)

**Pull request closed without merging**
