### PR TITLE
Varian private

### PR DESCRIPTION
**Pull request by celeron533**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Add private tags from Varian official DICOM Conformance Statements https://www.varian.com/why-varian/interoperability/dicom-statements

### CODE REVIEW

**Review by gofal — APPROVED** [review]
Thanks!

**Review by mrbean-bremen — COMMENTED** [review]
Can you please add an entry into the [change log](https://github.com/fo-dicom/fo-dicom/blob/development/ChangeLog.md)?

**Comment by celeron533** [comment]
> Can you please add an entry into the [change log](https://github.com/fo-dicom/fo-dicom/blob/development/ChangeLog.md)?

Updated. Thank you for the reminder.

**Review by mrbean-bremen — APPROVED** [review]
Thanks!

**Pull request merged**
