### PR TITLE
Multiple fixes in DicomClient for improved reliability of sending DICOM requests

### LINKED ISSUE #832: AsyncManualResetEvent.SetValue fails when called twice
See https://github.com/fo-dicom/fo-dicom/blob/742c0c1768d0e8b23b15eedf5dabfec26521ab04/DICOM/Network/AsyncManualResetEvent.cs#L83

The underlying issue is that the result is stored in Task.Result, which only accepts a value once. (A task can only transition once to Completed, Faulted or Cancelled).

It's probably worth investigating whether making a new TaskCompletionSource at this point is the better option. Should be safe, unless relying code is already waiting on the task of the previous TaskCompletionSource.

In any case, I believe it's bad form to not expose the boolean returned by TrySetResult on the TaskCompletionSource, because it hides the fact that this method can actually fail.

I also believe that there are scenarios in https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomClient.cs where this actually happens, because you can find usages of AsyncManualResetEvent here that set the flags with different values in different circumstances.

### LINKED ISSUE #833: DicomClient.IsConnected immediately returns true after construction of the DicomClient instance, even though no network communication has happened at all
See https://github.com/fo-dicom/fo-dicom/blob/fe9649e8b650947c8e31691b16e59c8a33f86c65/DICOM/Network/DicomClient.cs#L247

The implementation behind IsConnected checks for the isDisconnectedFlag in DicomService, but it's not because we've never been disconnected that it's safe to presume we are actually connected.

This has consequences, because the processing of the request send queue depends on this IsConnected property, and can cause requests to be lost in the noise before an association is even opened.

In fact, many of the flaky unit tests in this project (for example this one: https://github.com/fo-dicom/fo-dicom/blob/fe9649e8b650947c8e31691b16e59c8a33f86c65/Tests/Desktop/Network/DicomClientTest.cs#L66 ) can be directly linked to the unreliability of this IsConnected property.

### LINKED ISSUE #839: When releasing an association from DicomClient, don't set the completion flag before the association release response has been received
See https://github.com/fo-dicom/fo-dicom/blob/9f7810d1e60c303c5d11c8e49dce788805fe598f/DICOM/Network/DicomClient.cs#L821

The completion flag should be properly set in the "OnReceiveAssociationReleaseResponse" callback, not right after sending the association release request.

`Task.WhenAny` returns the task that "won", so the fix for this problem is rather simple: check which task won and only mark the completion flag in the "unhappy" cases 😄 

```csharp
                    var sendAssociationReleaseRequestTask = SendAssociationReleaseRequestAsync();
                    var sendAssociationReleaseRequestTimeoutTask = Task.Delay(millisecondsTimeout);
                    var waitUntilDisconnectionTask = _isDisconnectedFlag.WaitAsync();

                    var firstCompletedTask = await Task.WhenAny(
                            sendAssociationReleaseRequestTask,
                            waitUntilDisconnectionTask,
                            sendAssociationReleaseRequestTimeoutTask
                        ).ConfigureAwait(false);

                    if (firstCompletedTask == sendAssociationReleaseRequestTimeoutTask)
                    {
                        Logger.Debug($"DicomClient.DoSendAssociationReleaseRequestAsync timeout while trying to release the association");
                        SetCompletionFlag();
                    }
                    else if (firstCompletedTask == waitUntilDisconnectionTask)
                    {
                        Logger.Debug($"DicomClient.DoSendAssociationReleaseRequestAsync disconnected while trying to release the association");
                        SetCompletionFlag();
                    }
                    else if (firstCompletedTask == sendAssociationReleaseRequestTask)
                    {
                        Logger.Debug("DicomClient.DoSendAssociationReleaseRequestAsync association release request sent");
                    }
```

This problem surfaced in combination with the new 'forceDisconnect' parameter in DicomClient.DoSendAsync. When this is set to true, the connection is closed before the server has the chance to respond with an association release response, causing socket exceptions.

### LINKED ISSUE #841: DicomClient.Abort / AbortAsync never returns when not connected
```c#
new DicomClient().Abort();
await new DicomClient().AbortAsync();
```
### Expected behavior
If a client was never used, calling Abort() should be a noop.

### Actual behavior
Abort() never returns / the AbortAsync() task never completes.

### fo-dicom version and OS/platform
4.0.1 / current branch, Windows 18362

### PR DESCRIPTION
**Pull request by amoerie**
Fixes #833 
Fixes #832
Fixes #839 
Fixes #841 

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests (tests were already present for what I'm fixing)
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Wait for release of previous association before opening a new one
- Ensure association flags are actually set by automatically creating a new TaskCompletionSource in AsyncManualResetEvent
- Automatically create new associations if the previous association has been released but we're still connected
- Don't abort connection immediately when forceDisconnect is true and we've just sent an association release request
- When lingering an association (keeping it open in case we get more DICOM requests), add a bunch of extra checks to verify whether we can and should linger the association. When the linger triggers, double check if we can and should release the association. Furthermore, cancel lingering if other events supersede the linger (e.g. new requests come in, etc)
- Improve DicomClientTests by introducing client and server logging, which wraps the TestOutputHelper from xUnit and prints out association and request details

### CODE REVIEW

**Comment by amoerie** [comment]
I'll have to check later why two tests are still failing, for now the situation already seems to be improving.
Furthermore, we can now inspect the test logs to see the details of failing tests.

Unfortunately, AppVeyor doesn't seem to be able to provide the full log of one test, or am I missing something?

**Comment by amoerie** [comment]
@gofal Sometimes, some of these tests hang indefinitely. Is there any way to see the full test output when this happens?

**Comment by gofal** [comment]
@amoerie You mean on AppVeyor something like this test?:
    Dicom.Bugs.GH745.DicomClientShallNotCloseConnectionTooEarly_CEchoSerialAsync(expected: 10)
DICOM [Unit Tests].DLL
When build aborts because the total time exceeded 60 minutes. This test is the only one without a time duration and there is no link with the output. 
For me it seems that Appveyor just aborts after 60 minutes and the output of the test is not stored :-( So if you cannot reproduce it on your own system..
I will try to run the tests of the code of the pull request on my machine. maybe there the hang happens, then I can send you the output. So I will give it a try.

**Comment by amoerie** [comment]
I can very rarely reproduce the problem, I'm still investigating what happens. But thanks for the response, at least now I know I don't have to keep searching in AppVeyor. 👍

**Comment by gofal** [comment]
the test currently hang in SendAsync_MultipleTimes_AllRecognized, but this test has no output code.

**Comment by amoerie** [comment]
@gofal Hurray tests are green!

**Comment by amoerie** [comment]
The problem was a deadlock in HasAssociation and IsConnected, if two threads were simultaneously calling SendQueuedRequestsAsync.

The fix was to remove locking in HasAssociation because internally, the AsyncManualResetEvent has its own locking mechanism which should suffice to prevent race conditions.

**Comment by amoerie** [comment]
The following log snippet (which was run when my extremely verbose logging was enabled) demonstrates the locking problem:

```log
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : SetHasAssociationFlag: True
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Waiting for _lock in AsyncManualResetEvent.IsSet
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Acquired _lock in AsyncManualResetEvent.IsSet
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Released _lock in AsyncManualResetEvent.IsSet
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Waiting for _lock in AsyncManualResetEvent.Set
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Acquired _lock in AsyncManualResetEvent.Set
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [WAITING] SendQueuedRequestsAsync
    XUnitDicomLogger  DEBUG  11:56:50.772 # 27               DicomClient : [LOCK] Waiting for lock in DicomClient.IsConnected
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Waiting for _lock in AsyncManualResetEvent.IsSet
    XUnitDicomLogger  DEBUG  11:56:50.772 # 27               DicomClient : [LOCK] Acquired lock in DicomClient.IsConnected
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Acquired _lock in AsyncManualResetEvent.IsSet
    XUnitDicomLogger  DEBUG  11:56:50.772 # 27               DicomClient : [LOCK] Released lock in DicomClient.IsConnected
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Released _lock in AsyncManualResetEvent.IsSet
    XUnitDicomLogger  DEBUG  11:56:50.772 # 27               DicomClient : [LOCK] Waiting for lock in DicomClient.HasAssociation
    XUnitDicomLogger  DEBUG  11:56:50.772 # 21               DicomClient : [LOCK] Waiting for lock in DicomClient.IsConnected
    XUnitDicomLogger  DEBUG  11:56:50.772 # 27               DicomClient : [LOCK] Acquired lock in DicomClient.HasAssociation
    XUnitDicomLogger  DEBUG  11:56:50.772 # 27               DicomClient : [LOCK] Waiting for _lock in AsyncManualResetEvent.IsSet
```

**Comment by gofal** [comment]
👍 🎆 🍾

**Comment by amoerie** [comment]
@gofal Thanks for your assistance. Is there anything left that needs to happen before this PR can be merged?

**Comment by gofal** [comment]
@amoerie Thank you for digging into this not so easy stuff. 
Maybe if there are lines of code that are tricky, it woud be very helpful for other developers to come in future, if they had some comments, why this call has to happen here and why it should not be removed or similar. But that would be a nice bonus.

The usual progress is, that the pull request stays open for some time to give developers, that are not online every day, the chance to ad thoughts and comments.
Lets give the communitiy a week or two?

**Comment by amoerie** [comment]
Sure thing! I’ll try to add some comments or logging in tricky places, but I have to say that the main problem was seeing the bigger picture and understanding how all the flags work together. It’s not as if there’s one magical line of code that’s making it all work.

The biggest problem with DicomClient is that it must handle all methods and callbacks in all situations. What if we receive SendAsync with a different host and port while we are sending requests? What if we receive OnAbort while we try to create a new association? What if we linger the association but the connection has been lost? etc. etc. All of this must be supported from multiple threads, and every thread must see the correct results. 

One big missing thing is unit tests for the linger behavior by the way.. I verified everything still works by testing manually, but this mechanism is easily broken.

**Comment by gofal** [comment]
if this one class DicomClient has to deal with so many things, would it be better design to split it into several classes?

**Comment by amoerie** [comment]
It's funny you should say that, I'm working on exactly this solution over in my experimental branch: https://github.com/amoerie/fo-dicom/tree/DicomClientRewrite/DICOM/Network/Client

This experimental branch contains a DicomClient state machine, i.e. every 'state' of the DicomClient is a separate class that handles its own callbacks and events. The big benefit is that you can reason about events much more simply, and that flags (TaskCompletionSource) and timers only exist in the appropriate states. 

Cancellation is implemented across the flow using cancellation tokens, and I tried to be backwards compatible with as much as possible of the current DicomClient API. I mostly succeeded in that, with a few notable exceptions:

- The host, port and timeout parameters are now passed into the constructor of DicomClient, instead of being parameters of the SendAsync method. This makes A LOT more sense, as the current DicomClient keeps sending requests to the current association anyway. Consequentially, it strongly depends on when you call AddRequest whether it will be sent to the previous host and port or to the new host and port you passed. In fact, I don't think one instance of DicomClient fully supports sending to different hosts and ports at all, today.

- The methods 'Release' and 'Abort' are gone. If you want to cancel the work the DicomClient is doing, just mark the cancellation token as cancelled, and that should gracefully stop the whole process, releasing the association and all. The abort behavior is currently not supported, but I would be in favor of implementing IDisposable on DicomClient, in which case Dispose() would simulate the abort behavior.

If you check out my branch, you'll see I adapted the existing test suite for DicomClient to test my new implementation, and the tests seem to be very stable. 

I would be very interested in your feedback on this design proposal. I realize it's a pretty impactful API change (and perhaps the new DicomClient could live side by side with the old one under a different name for a while) but it seems to bring a lot of benefits.

**Comment by gofal** [comment]
Will merge this for now. Looking forward to see a new pull request for the split up DicomClient - if possible with a different classname or different namespace to have both work in parallell to make miration easier.

**Pull request merged**
