### PR TITLE
Upgrade to platform toolset v141 and Windows SDK 10.0.16299

### PR DESCRIPTION
**Pull request by anders9ustafsson**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Upgrade MSVC platform toolset to v141 (Visual Studio 2017)
- Upgrade (minimum) Windows SDK target version to 10.0.16299 (version 1709. Fall Creators Update)

### CODE REVIEW

**Comment by gofal** [comment]
Updating buildtools to visual studio 2017 is fine, since now studio 2019 will be released, so its fine if we don't force developers to install studio 2015 components.

**Comment by gofal** [comment]
About updating the WindowsTargetPlatformVersion: does that mean that this code will not run in windows 8? the code itself does not call any significant windows api, so updating to windows 10 sdk brings advantages? 
I can be totally wrong, of course, but this seems like changing to newer .net version without using some of the new features, so making the requirement to the executing system tighter without needing it and therefore limiting the usability?

**Comment by anders9ustafsson** [comment]
Yes, you are right, this will limit usage to Windows 10. I (probably) can revert the SDK changes and update the pull request.

**Comment by anders9ustafsson** [comment]
Have now reverted to 8.1 for the desktop libraries. Please review.

**Pull request merged**
