### PR TITLE
Make use of MemoryMappedFile when reading large DICOM files

### PR DESCRIPTION
**Pull request by anders9ustafsson**
I can't get any peace over #17, I am still concerned that it adds unnecessary overhead when loading pixel data, in particular for more complex pixel data types.

I have therefore implemented this alternative approach where `Data` is lazily initialized instead. This change alone leads to 2.5 times faster pixel data access for the **first** pixel on my computer. I also exchanged all `Parallel.For` statements with regular `for` constructs, which made the speed-up even bigger, 3 times the `MappedFileBuffer`/`Parallel.For` approach.

There were no noticeable differences in memory consumption between the two approaches. I have tested with images of different sizes, with the largest image up to 37 MB. But I understand that the `MappedFileBuffer` need emanated from dealing with considerably larger images.

@hdesouky @IanYates @GMZ I would appreciate it very much if you could take your time to review this alternative implementation thoroughly. @hdesouky In particular it would be great if you could test with the large images that you typically are facing. And if you have the possibility, it would be great if you could share one of these very large images so that I could also test it locally.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
Sorry, I did not think this one through. Using the `Lazy` construct on the input `IBuffer` argument in the constructor is of course completely error-prone; potentially the buffer data could change or be cleared before the `_data` array in the pixel data object is initialized. 

So the current proposal is not acceptable. On the other hand, the performance tests **did** show considerable improvement even with relatively large (37 MB) images, so there is obviously potential for improvement of the current implementation for at least small- to medium-sized images. I still we need to address that issue.

**Comment by IanYates** [comment]
I'm travelling at the moment (visiting a new client site) but will review and chime in when I am back home on the weekend :)  It's a worthy goal to try to defer some work to being lazily evaluated if possible

**Comment by anders9ustafsson** [comment]
OK, here is my more comprehensive, well thought through :-) proposal.

From the MSDN documentation for [MemoryMappedFile](https://msdn.microsoft.com/en-us/library/system.io.memorymappedfiles.memorymappedfile.aspx), I draw the conclusion that `MemoryMappedFile.CreateNew` which is used in the `MappedFileBuffer` implementation does allocate additional memory, and is primarily suitable for inter-process communication. The way I see it, we would benefit more from using `MemoryMappedFile.CreateFromFile` instead. If this instantiator was used when creating a new `DicomFile`, we would not have to copy the DICOM file into memory in the first place.

For this purpose, I have therefore added two method overloads `DicomFile.OpenLarge`, which under the hood benefits from `MemoryMappedFile.CreateFromFile`. Instead of the `FileByteSource` used in `DicomFile.Open(string)`, `DicomFile.OpenLarge` uses the new `MemoryMappedFileByteSource` class, which internally uses `MemoryMappedFile`. If this works as I have intended, this approach should avoid the copying to memory that would otherwise be an issue with the approach taken in the `DicomFile.Open` overloads.

Furthermore, I have completely reverted the implementation of the different `IPixelData` implementations to how they were before 1.1.0, i.e. `MappedFileBuffer` usage has been removed. I do believe that this "older" approach is more memory and speed efficient than the `MappedFileBuffer` approach, since the `MappedFilBuffer` approach did require new memory allocation *and* contained additional overload in the form of byte conversion to and from other types.

The`Parallel.For` constructs are still removed; from experience I would consider the blocks within the `Parallel.For` statements to be too small for efficient parallelization. Performance testing on various images indicates that this is indeed the case.

@hdesouky @IanYates @GMZ @aerik Please take a thorough look at this proposal of mine. In particular @hdesouky , if you could try using `DicomFile.OpenLarge` on your very large DICOM files and review the performance, that would be absolutely invaluable. If you have possibility to share a few large files, that would also be just great; so far the largest DICOM sample I have been able to retrieve from Internet is at about 37 MB.

**Comment by anders9ustafsson** [comment]
BTW, in this new implementation I have also relaxed the behavior of the `IByteSource.Require` implementations to return `false` rather than throw an exception, and accordingly I have changed the behavior in `DicomReader` to terminate reading when the `Require` check returns `false`. Ideally this should only have a positive impact on *fo-dicom*'s parsing operations.

**Comment by anders9ustafsson** [comment]
One further comment: the `Lazy` construct in the first commit also provided unnecessary overhead, with the additional risk of potentially changing or clearing the data that was going to be used in the initialization. That was why I abandoned the `Lazy` approach and reverted to the pre-1.1.0 approach instead.

**Comment by anders9ustafsson** [comment]
If you eventually agree that this is a feasible approach, the method name `OpenLarge` might still need to be reconsidered. Maybe `OpenMapped` or something instead?

**Comment by GMZ** [comment]
@anders9ustafsson, @hdesouky, @IanYates, I'm confused as to what original issue was, I've never had an issue loading or using large files? 
in my production viewer which is still rocking the my own version of Fo-Dicom prior to all this consolidation work 1.0.38.1(the point one on the end is the version still on my fork) I'm using it open 1.2 GB tomo images with out issue, whats slow?, in my opinion its a perception/expectation problem.
Clinical feedback I've had from customers is opposite to this line of thinking.

That being said someone using fo to view 6-7 thousand image CT studies is going to have a better perception of the speed vs some loading Tomo studies with 10 1+ GB images. 

Fo is not fit for every purpose, for this reason I integrate with other specialist software for those purpose's

What I have noticed is that depending on what transfer syntax the pixel data is encoded with more effects the load time than anything. i.e j2k lossless 3 time slower than commercial implementations I've used, and I'm also seeing strange issues from some modalities that add strange failures in JPG render pipline that cause issues in fo- and clearcanvas.

I'll download the latest checkin and do some comparisons.

**Comment by anders9ustafsson** [comment]
@GMZ Many thanks for these comments. Have you had the chance to test the 1.1.0 release on NuGet, or would you be able to run some tests? It would be very valuable to get your input on how 1.1.0 performs w.r.t. image loading of those 1 GB files compared to your own 1.0.38.1 build.

Interesting to get your point on transfer syntax as well. *fo-dicom* are using fairly old code bases for J2K and JPEG decoding/encoding (I even think they originate from the *mdcm* era). The original C/C++ projects have (probably) evolved quite a lot since the snapshots for *fo-dicom* were grabbed. Maybe we should also consider to update to more recent snapshots of these C/C++ libraries as well, to benefit from the latest stability and performance improvements in these code bases?

**Comment by anders9ustafsson** [comment]
@GMZ And by the way, do you know somewhere where I can get hold of ~1 GB samples for my own testing purposes?

**Comment by GMZ** [comment]
I'll see if I can anonymize some for you

**Comment by aerik** [comment]
@anders9ustafsson - I like your last proposal.  I'm only dealing with maybe 25MB files, though occasionally I am loading every frame of some CTs into memory, but I haven't had any problems with the old approach.  For my purposes, I can throw memory at the problem but don't want to sacrifice speed.

**Comment by GMZ** [comment]
@aerik opening every frame in memory is wasteful and terribly inefficient, My customers capture CT studies with an average of 6000 - 7000 images per study (we send all thin data to our PACS)

I use a method where by I open every file, however this does not render the pixel data..
By default fo defers loading the pixel data so I only ever have the pixel data loaded for the frame in each series that is being displayed so for a 6-7 thousand image CT study in a 2x4 matrix only 6 images are rendered to the screen along with a thumbnail for each series (rendered to a max of 80x80pixels) this ensures that memory for the app is kept around 400 MB

that same study rendered with Leadtools (commercial engine) loading every frame to RAM was 1.8GB ram the 2 approaches have very different results I still believe the memory mapped file is not needed if you approach the problem in this way. As a side note we also found that loading everything into ram caused other performance issue and we were having to restart reporting workstations during the day sometimes 2-3 times a day using the other approach I've described 0 restarts during the work day. 

Reporting time is the key if a workstation crash's or needs reboot this can easily cause 20 min of time a radiologist/cardiologist is not reporting this is significant revenue loss to a practice/hospital

My preference is the revert memory mapped file for the original implimentation, has anyone done any benchmarking of render times? I'm keen to understand what kind of load times/ wait times we are talking about.... my experience is that image loading with fo is still faster that with viewers from the major PACS vendors (with the exception of J2K howver as I've raised I believe this to be fixable by overhalling the native libs)

**Comment by aerik** [comment]
@GMZ  Thanks, but I have a completely different application (web based, I load each frame in the server, pass it to the client to cache, and then unload it from the server) and fortunately most of the images we're dealing with are CR / DX.  Honestly, really large CTs are probably completely infeasible in my application, but for our customers and our use-cases, that's probably okay :-)

**Comment by anders9ustafsson** [comment]
I have renamed the new overloaded methods to `OpenMemoryMapped` and placed them in a separate file (via partial class declaration) now. Placing them in separate files should make it easier at a later stage to include/exclude the functionality depending on platform compatibility (read *portable class libraries*).

@hdesouky Have you had a chance to evaluate this PR further, in particular with respect to the previous PR #17?

**Comment by anders9ustafsson** [comment]
I made some isolated performance tests on the `IPixelData.Render` implementations, and came to the conclusion that usage of `Parallel.For` does indeed speed up the render process. I have therefore reverted to `Parallel.For` usage for the outer loop in the `Render` methods.

It should be noted, that this part of the rendering is normally not a bottleneck, but the original implementation (with `Parallel.For`) has worked well this far so I should not change it here.

**Comment by anders9ustafsson** [comment]
@hdesouky @IanYates @GMZ @aerik I would like to pull this request, since I consider to offer both the performance of the pre-1.1.0 image rendering and an option for mapping very large DICOM files into the logical address space. At this point, does anyone have any concerns with this PR? Otherwise I will pull it by the end of this week.

**Comment by hdesouky** [comment]
I know this is a late participation, too busy lately. The main issue as @GMZ  stated is having to load large study with more than 1000 images for CT (not large images like CR or DR).

Create mapped file section from file will be much more efficient to avoid unnecessary loop to read the pixels from memory first to create memory mapped section from the heap. (i like this approach more).

And to add more, when your application is not 64 bit or the operating system is 32 bit, you will hit the wall of the 2 GB process memory limit (1.5 GB in reality) very quickly when loading this large study and rendering a 3D volume (using VTK ActiViz).

@GMZ  your solution of loading in memory what you currently displaying will save the memory but will incur additional performance issue since when you load new file to display you will had to go through the overhead of reading the DICOM file and parsing it each time. Which will lead to unpleasant experience to the users who likes to see more smooth image scrolling.

@anders9ustafsson  OSIRIX has a nice samples library (http://www.osirix-viewer.com/datasets)
Check the OBELIX sample.

Make sure to convert the dataset to uncompressed format since it is stored using JPEG 2000.

**Comment by anders9ustafsson** [comment]
@hdesouky Many thanks for your further explanation and the OBELIX sample advice.

To me it still seems inefficient to use the `MemoryMappedFile` object as a data container in all the different `IPixelData` implementations. For most of the pixel data types (except `GrayscalePixelDataU8`) it involved data conversion both in the constructor and in the call to the `Data` getter, and you also needed to allocate new file memory for every single image.

I beleive that the goal with the pixel data implementations is that they should be as efficient as possible for single images, and then it should be up to the consumer of the *fo-dicom* library to use the output data as efficiently as possible in the different multi-image scenarios.

If the scenario is that you have a large number of medium sized images, and you want to use the `MemoryMappedFile` approach, to me it seems more efficient to create *one* `MemoryMappedFile` object to contain all pixel data; loop over the collection of images, initialize a pixel data object for each image via the relevant constructor or the `PixelDataFactory.Create` method, copy the contents of the pixel data object to the single `MemoryMappedFile` object and then immediately dispose of the pixel data object before you move to the next image in the loop.

Does this sound like a reasonable approach, or am I missing something?

**Comment by hdesouky** [comment]
But loading all pixel data initially is not good practice. it should be done progressively as user navigate through images. But it seems to be the best approach to go if we are able to avoid loading the whole thing in one shot.

In the other hand, i had something i want to share with you that may add to this discussion. I implemented a new class inherited from DicomImage, called CachedDicomImage. This class uses .Net caching infrastructure to cache constructed DicomImage Bitmap in memory and let the caching engine decide when to remove unused objects for long time or when the OS had a memory stress.

This same idea can be used with PixelData where these objects can be stored in cache instead of heap.

Below is the code of the current implementation for Bitmaps. what do you think

...
    public class CachedDicomImage : DicomImage, IDisposable
    {
        private MappedFileBuffer _buffer;
        private Guid _instanceId = Guid.NewGuid();
        private static System.Runtime.Caching.MemoryCache _memoryCache;
        private bool _disposed;
        static CachedDicomImage()
        {
            //System.Runtime.Caching.ObjectCache.Host
            var config = new System.Collections.Specialized.NameValueCollection();
            config.Add("cacheMemoryLimitMegabytes","300");
            config.Add("physicalMemoryLimitPercentage", "30");
            config.Add("pollingInterval","00:02:00");
            _memoryCache = new System.Runtime.Caching.MemoryCache("CachedDicomImage", config);
        }

        public static void ClearMemoryCache()
        {
            var entries = _memoryCache.Select(kvp=> kvp.Key);
            foreach (var item in entries)
            {
                _memoryCache.Remove(item);
            }
        }
        public CachedDicomImage(DicomDataset dataset, int frame = 0)
            : base(dataset, frame )
        {

        }

        public CachedDicomImage(string fileName, int frame = 0)
            :base(fileName,frame)
        {

        }

        ~CachedDicomImage()
        {
            Dispose(false);
        }

        public override double WindowCenter
        {
            get
            {
                return base.WindowCenter;
            }
            set
            {
                base.WindowCenter = value;
                ClearCache();
            }
        }

        public override double WindowWidth
        {
            get
            {
                return base.WindowWidth;
            }
            set
            {
                base.WindowWidth = value;
                ClearCache();
            }
        }
        public override System.Drawing.Image RenderImage(int frame = 0)
        {
            lock (this)
            {
                if (CurrentFrame != frame)
                {
                    ClearCache();
                }

                if (_buffer == null)
                {
                    var image = base.RenderImage(frame);
                    var memStream = new System.IO.MemoryStream();
                    image.Save(memStream, System.Drawing.Imaging.ImageFormat.Bmp);
                    _buffer = new MappedFileBuffer(memStream.ToArray());

                    CacheImage(memStream);
                    return image;
                }
                else
                {

                    return GetCachedImage();
                }
            }
        }

        public void ClearCache()
        {
            if (_buffer != null)
            {
                _buffer.Dispose();
                _buffer = null;
            }
            _memoryCache.Remove(_instanceId.ToString());
        }

        private void CacheImage(System.IO.MemoryStream memStream)
        {
            var policy =new System.Runtime.Caching.CacheItemPolicy
            {
                SlidingExpiration = TimeSpan.FromMinutes(5),
                RemovedCallback = OnRemoveCachedImage
            };
            //_memoryCache.GetCount()
            _memoryCache.Add(_instanceId.ToString(), memStream, policy, null);

            System.Diagnostics.Debug.WriteLine("Memory : {0} , {1}", _memoryCache.PhysicalMemoryLimit, _memoryCache.CacheMemoryLimit);
        }

        private System.Drawing.Image GetCachedImage()
        {
            var memStream = _memoryCache.Get(_instanceId.ToString()) as System.IO.MemoryStream;

            System.Drawing.Bitmap image;
            if (memStream == null)
            {
                memStream = new System.IO.MemoryStream(_buffer.Data);

                CacheImage(memStream);
            }
        
            image = new System.Drawing.Bitmap(memStream);
        
            return image;
        }

        private static void OnRemoveCachedImage(System.Runtime.Caching.CacheEntryRemovedArguments e )
        {
            var memStream = e.CacheItem.Value as System.IO.MemoryStream;
            memStream.Dispose(); 

        }

        protected virtual void Dispose(bool disposing)
        {
            if(!_disposed)
            {
                ClearCache();
                _disposed = true;
            }
            
        }
        public void Dispose()
        {
            Dispose(true);
        }
    }
...

**Comment by GMZ** [comment]
Thanks for the info @hdesouky 32 bit machine? rally its 2015 right our pacs runs as an area wide pacs accross 46 hospitals in country Australia 80% of the workstations run windows XP and not one them is 32 bit, this should not even be a consideration. I've not used ITK or VTK I use direct X to load 3D volumes, this is not a consideration for me because 32bit systems a not a part of the clinical landscape for radiology, radiographers and radiologists typically have the best systems, all the 3D systems I've seen and used tend to be lagy, slow, and down sample when rotating on 32 bit systems (some have the same problem 64 bit systems) this is all beside the point.
The point is performance, personally I don't see the need for the memory mapped file, I have none of the performance issues that you seam to? but I also seem to be in the minority

**Comment by anders9ustafsson** [comment]
Many thanks for this contribution, @hdesouky ! 

What is your experience with this new class? Under what conditions is the `CachedDicomImage` preferable over the regular `DicomImage`?

Since `CachedDicomImage` is a separate class, of which no other type in the *DICOM*  library is dependent, I see no problems of including it in the library as long as it fills a requested purpose. Please prepare a PR if you deem the `CachedDicomImage` class to add value to the *DICOM* library. One word of caution, though; as part of *this* PR I removed the `MappedFileBuffer` class, so you may need to re-introduce it.

**Comment by hdesouky** [comment]
CachedDicomImage used to store the generated bitmaps on memory to avoid building the bitmap from the DicomImage from pixel data through the rendering pipe line.

It will depends on the available memory on user PC and will remove bitmap objects from memory if not used for long time.

This class was mainly used to solve a problem with CR/DR images (3 and more mega pixels images) where image manipulation like zoom and pan doesn't require building the bitmap from scratch an image is needed.

I was suggesting of a way instead of using Mapped Memory File, to figure out how to use the same technique to cache pixel data instead of keeping it on the heap all the time.

@GMZ I totally understand your case, but not all customers/enterprises are the same. E.g. here in Egypt most Radiologist Laptops they use for remote diagnosis are not that high spec (Teleradiology) also i saw some cases where these users are using Surface Pro.

Even the OS is 64 Bit, they don't have the luxury of having large RAM (curse the economy for that).

I think, if we can refactor DicomImage to support PixelData on heap or on Cache will close this issue and the need of memory mapped file will not be necessary. What do you think?

@anders9ustafsson I will do so ASAP.

**Pull request merged**
