### PR TITLE
AAssociate Request/Reponse SOP Class Extended Negotiation. Connected to #241

### PR DESCRIPTION
**Pull request by zcr01**
Implements Issue #241 

Changes proposed in this pull request:
- Add a collection of Extended Negotiaion objects to DicomAssociation
- Write/read Extended Negotiation to/from RawPDU (current support for StudyRootQueryRetrieveInformationModelFIND, PatientRootQueryRetrieveInformationModelFIND, StudyRootQueryRetrieveInformationModelMOVE, PatientRootQueryRetrieveInformationModelMOVE, with a pattern for implementing more.
- Allow users to implement new extended negotiation sub items at their service level through DicomExtendedNegotiation.AddSubItemCreator()

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@zcr01 Many thanks for providing this great enhancement! We will review for inclusion it and provide feedback as soon as possible.

**Comment by anders9ustafsson** [comment]
@zcr01 Sorry for the delay, I have been busy with other things. I have looked your PR over, and I think it will make a good addition to *fo-dicom*. Many thanks!

The only thing I am concerned about is the lack of API documentation. Could you please add at least rudimentary documentation on the types and the methods that you have added?

Thanks in advance!
Anders

**Comment by zcr01** [comment]
Sure, I'll try to get that done soon.

**Comment by anders9ustafsson** [comment]
@zcr01 I took over this PR #272 in a separate PR where I re-formatted some of the code and added very basic API documentation. Therefore I am closing this PR, but all your work is included in the replacement PR. Many thanks for contributing!

**Pull request closed without merging**
