### PR TITLE
Removing the Init classes from NLog and Serilog logging adapters

### PR DESCRIPTION
**Pull request by IanYates**
as they don't serve any useful purpose

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
Great, thanks for taking care of this, Ian!

If you don't mind, I will also update the logging assemblies to make use of the attributes in the [SharedAssemblyIfo.cs](https://github.com/fo-dicom/fo-dicom/blob/development/SharedAssemblyInfo.cs) file as part of the 1.1.0 release preparation in issue #29.

**Comment by IanYates** [comment]
I knew there was something else you raised - serves me right for squeezing this in at work :)
I don't mind if you make the change at all

**Comment by anders9ustafsson** [comment]
No worries, Ian :-) Change is now included in PR #32 . 

One thing I came to think of when locally testing the *NuGet* packages: what do you need to do to obtain output from Serilog? Or, to rephrase the question, how can you configure the *Serilog* logger to dump output in the desired sink?

If I understand *Serilog* documentation correctly, it is possible to steer level and location of output via the *app.config* file, but then you need to enforce the *Serilog* instance to read from this configuration file, right?

Am I missing something, or does the *Serilog* logger need to be updated so that the logger can be re-configured after instantiation?

**Comment by IanYates** [comment]
I'll write the wiki page over the weekend around how to configure logging in fo-DICOM and then have a section for Serilog and NLog.
You can get Serilog to use app.config but I personally have steered away from that since I didn't need the arbitrary flexibility it provided.  Even if that is the desired use case you still need to tell Serilog to read from there as part of its bootstrap lines of code.

**Comment by IanYates** [comment]
This is a pretty good overview - https://github.com/serilog/serilog/wiki/Configuration-Basics and this provides a good idea of the various sinks to which you can send your log data - https://github.com/serilog/serilog/wiki/Provided-Sinks.  
I'll refer to bits of these in the wiki page.

The fo-dicom / Serilog package provides an fo-dicom logger implementation that accepts a Serilog logger instance.  I suppose for ease of configuration it could also have a no-parameter constructor that uses Serilog's global Log.Logger instance.

**Comment by anders9ustafsson** [comment]
But the `SerilogLogger` class is `internal` and is only instantiatable from the outside via by instatiating `SerilogManager`, right? 
Does `Serilog.Log.ForContext("fo-DICOM", name)` come with a set of pre-defined sinks? 
If I want to set output level or sink (programmatically or via *app.config*), is there any way I can do that with the current implementation of `Dicom.Log.SerilogLogger`? Or is there no need?

**Pull request merged**
