### PR TITLE
Use CommunityToolkit.HighPerformance (#1473)

### LINKED ISSUE #1473: Upgrade Nuget package to use CommunityToolkit instead of Microsoft toolkit as it is depreciated.
**What is, according to you, missing from fo-dicom? Please describe.**
Currently, Fo-Dicom is using Microsoft.Toolkit.highperformance nuget package which is depreciated and it's alternate is Communitytoolkit.Highperformance. 

**Describe the solution you'd like**
Change Nuget package to Communitytoolkit.Highperformance from Microsoft.Toolkit.highperformance

**Describe possible alternatives or existing workarounds you've considered**
A clear and concise description of any alternative solutions or existing workarounds you've considered.

### PR DESCRIPTION
**Pull request by akojo**
Microsoft.Toolkit.HighPerformance is no longer maintained. Switch to using its successor CommunityToolkit.HighPerformance.

Fixes #1473.

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]
Thanks!

**Review by gofal — APPROVED** [review]
Thanks!

**Comment by jaime-olivares** [comment]
This is causing issue in production when fo-dicom is installed from nuget. 
The mentioned library (Microsoft.Toolkit.HighPerformance) is no longer installed along with fo-dicom and throws a runtime exception.
It is required to include the library explicitly in the csproj.

**Comment by mrbean-bremen** [comment]
It should have been replaced by `CommunityToolkit.HighPerformance` in this PR. You mean it is still referenced somewhere in the code?

**Comment by jaime-olivares** [comment]
What I mean is: all those using fo-dicom 5.0.3 and previous ones may have issues because of the dependency Microsoft.Toolkit.HighPerformance is marked as deprecated in nuget, and it is not automatically installed along with fo-dicom.

**Comment by mrbean-bremen** [comment]
I'm still not sure I understand correctly. I understand that there has been no new release with this PR included yet (which would help if the user is able to update), but I'm not sure what can be done for older releases. I'm sure I'm missing something...

**Comment by jaime-olivares** [comment]
For older releases, I am making the suggestion to include `Microsoft.Toolkit.HighPerformance` explicitly in the project in case a new attempt to build fails.

**Comment by mrbean-bremen** [comment]
I don't know the nuget mechanism in this case (e.g. with a deprecated package) - `Microsoft.Toolkit.HighPerformance`  was already included in the csproj, do you mean it has to be included in the nuget target or somehow directly in the nuget package? Sorry for the dumb questions...  @gofal will probably better understand what you mean here.

**Comment by gofal** [comment]
I understand this as a hint to end users, if they search here for a solution because they are facing this Issue. If they wann so stay with Version 5.0.3, they have to reference the deprecated package, too, and should not rely that it is installed together with fo-dicom

**Pull request merged**
