### PR TITLE
Automatically set Setup.ServiceProvider using a hosted service

### LINKED ISSUE #1613: Dependency injection is not working as expected
**Describe the bug**
When you use Fellow Oak DICOM with a dependency injection container, simply calling .AddFellowOakDicom() is not sufficient. 
So, at the very least, I think our documentation is lacking in this area. 
I also believe that we should do better and that DicomSetupBuilder should not be necessary for the most common scenario.

**To Reproduce**
Given the following Program.cs (.NET 7 worker template)

```csharp
using FellowOakDicom;
using FellowOakDicom.Imaging;
using FellowOakDicom.Imaging.NativeCodec;

var host = Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
        logging.AddConsole();
    })
    .ConfigureServices(services =>
    {
        services.AddFellowOakDicom();
        services.AddImageManager<ImageSharpImageManager>();
        services.AddTranscoderManager<NativeTranscoderManager>();
        services.AddHostedService<Worker>();
    })
    .Build();

host.Run();

public class Worker : IHostedService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        var dicomFile = await DicomFile.OpenAsync("testfile.dcm");
        var dicomImage = new DicomImage(dicomFile.Dataset);

        using var image = dicomImage.RenderImage();

        if (image is ImageSharpImage)
        {
            _logger.LogInformation("Success!");
        }
        else
        {
            _logger.LogError("Image is of type {ImageType}", image.GetType());
        }
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

This produces the following log entries:

```log
fail: Worker[0]
      Image is of type FellowOakDicom.Imaging.RawImage
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
```

This fails because DicomImage.RenderImage statically retrieves the ImageManager, which is taken from DicomSetupBuilder.
However, DicomSetupBuilder is never configured automatically.

The workaround is this:

```csharp
var host = Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
        logging.AddConsole();
    })
    .ConfigureServices(services =>
    {
        services.AddFellowOakDicom();
        services.AddImageManager<ImageSharpImageManager>();
        services.AddTranscoderManager<NativeTranscoderManager>();
        services.AddHostedService<Worker>();
    })
    .Build();

/* This line must be added to get the expected behavior. I can't think of any other library that requires this. */
DicomSetupBuilder.UseServiceProvider(host.Services);

host.Run();
```

**Expected behavior**
I would expect that calling services.AddFellowOakDicom is sufficient.

**Screenshots or test DICOM files**
See example 

**Environment**
This is my .csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="fo-dicom" Version="5.1.1" />
      <PackageReference Include="fo-dicom.Codecs" Version="5.10.6" />
      <PackageReference Include="fo-dicom.Imaging.ImageSharp" Version="5.1.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="testfile.dcm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
```

### PR DESCRIPTION
**Pull request by amoerie**
Fixes #1613

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Automatically register a hosted service that calls `DicomSetupBuilder.UseServiceProvider(..)` on startup

### CODE REVIEW

**Comment by amoerie** [comment]
@gofal This does not address the fact that we have a lot of static APIs, but only addresses the problem where the static Setup.ServiceProvider was not set automatically in .NET Core applications. I've tried to keep the changes to a minimum.

**Comment by gofal** [comment]
You are mixing up ".net core" and "asp.net core". 
.net core applications do not automatically have the hosting stack loaded and started. Build a smlall .net core tool to query some pacs or to do some conversions or whatever. my small tool took 12 MB memory after startup and starts very quickly. but with yout change not this tool starts with approx 40mb memory and has some little latency on startup. because now the .net core also has to start all the hosting environment.

Furthermore this change introduces more dependencies to Microsoft.Exntensions.Hosting that are not used elsewhere.

but when you are talking about asp.net core, where you have a program with a hostbuilder and then all the logic is done within some requestpipelines etc, then the hosting is done anyway.
This is why I startet the project fo-dicom.aspnetcore. this is the right place to add such convenience code and helper methods etc that are asp.net core specific.

**Comment by gofal** [comment]
In project "fo-dicom.aspnetcore" there is already a ServiceCollectionExtension `UseFellowOakDicom`, which actually does call `AddFellowOadkDicom` and then registers a hosted service, where in the factory method the serviceprovider is set to the static DicomSetup property.
So use this code, then you do not have to call the DicomSetupbuilder.UserServiceprovider anywhere else.

The project fo-dicom.aspnetcore is a copy of some code that we are using in production. I do not consider this project as mature enogh to be released, but if you want to use it, then i will deploy it on next release.

The namings of the methods there are now of course open to discussion, maybe "UseFellowOakDicom" is not clear enough and "AddFellowOakDicomToAspnetCore" would be longer but more explaining.... ?

**Comment by amoerie** [comment]
Okay I hear you. If adding a hosted service to the base fo-dicom library is not an option, we could maybe release a fo-dicom.AspNetCore package that only contains the minimal necessary bits to fix this problem? We can leave the other code there as-is, but maybe make them internal or private until they're mature enough.

As for the naming, I think UseFellowOakDicom would be really confusing, because UseABC is typically used for middleware in the IAppBuilder interface. So I would definitely change it to something else.

I checked with some other libraries how they tackle this problem, but none of them still have public static APIs scattered in various places. If you only have one entry point, this problem is a lot easier. (For example, EasyNetQ has a single RabbitHutch class that deals with this exact problem)

To be honest, we could do this:

- Release fo-dicom.AspNetCore
- It contains an extension method `AddFellowOakDicomToAspnetCore`
- Document that you need this nuget package and extension method if you use Microsoft.Extensions.Hosting
- Inside, we implement a HostedService that calls DicomSetupBuilder.UseServiceProvider inside StartAsync

Or... we could just tell people to invoke DicomSetupBuilder.UseServiceProvider, until we provide DI-friendly alternatives to things like `DicomFile.Open(..)` and `new DicomImage(..)`

So maybe we should just focus on the additional DI-friendly APIs, and simply document this issue in the README.

**Pull request closed without merging**
