### PR TITLE
Fix incorrect set OverlayOrigin

### PR DESCRIPTION
**Pull request by kira-96**
Fixes # .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- When set the OriginY / OriginX of `DicomOverlayData`, the dataset will not change as expected, because the positions of OriginY and OriginX are reversed when updating the dataset.

### CODE REVIEW

**Comment by amoerie** [comment]
Looks good to me!

Could you:

- Add tests for this? The getters already have tests here: https://github.com/fo-dicom/fo-dicom/blame/development/Tests/Desktop/Imaging/DicomOverlayDataTest.cs#L129
- Add your name to the CONTRIBUTORS.md file in the root of the project?
- Add an entry in the CHANGELOG.md that describes your change?

**Comment by kira-96** [comment]
I've used unit tests [L129](https://github.com/fo-dicom/fo-dicom/blame/development/Tests/Desktop/Imaging/DicomOverlayDataTest.cs#L129) and [L144](https://github.com/fo-dicom/fo-dicom/blame/development/Tests/Desktop/Imaging/DicomOverlayDataTest.cs#L144) for test, and everything is OK.
I also updated the CHANGELOG and CONTRIBUTORS files.
I'm very glad to be a contributor.

**Comment by kira-96** [comment]
I'll add a test case for the setter method later.

**Comment by kira-96** [comment]
Oh, I didn't seen that there has another `DicomOverlayData`. Now everything is OK.

**Comment by amoerie** [comment]
@gofal This PR looks pretty complete to me, awaiting your final judgement 😉

**Pull request merged**
