### PR TITLE
Added Practice Build Private SOP Classes. Connected to #589

### PR DESCRIPTION
**Pull request by JustSomeHack**
Fixes # .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [ ] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Added Practice Builder Private SOP Classes
-
-

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@deyung Many thanks for your PR. However, to make this PR worthwhile of pulling I would like to see a more comprehensive list of private UIDs. 

There is support already today for adding single private UIDs to the list of known UIDs via `DicomUID.Register()`, see for example [this](https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Desktop/Network/DicomServerTest.cs#L218-L239) unit test. On the top of my head I can't remember in which *fo-dicom*  release it was added, but it should at least be available in the 3.1.0-alpha NuGet release. If you only have a few private UIDs to add, this is the recommended approach.

Alternatively, if you could consider to add a more comprehensive list of known private UIDs, that would make a very good contribution to *fo-dicom*. [Here](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/storage/storage.html) is quite an extensive list; if you could pick all the **Private** prefixed UIDs from this list and add to the *DicomUIDPrivate.cs* file, that would be very beneficial.

Also, please be as faithful to the official name as possible when naming the `DicomUID` fields. For example, I would like the field to be named `PrivateERADPracticeBuilderReportDictationStorage`. And follow the API documentation principles used in the *DicomUIDGenerated.cs* file.

If you are willing to extend your PR according to these requirements, I would be more than happy to pull it in. I will create an issue #589 that you could refer to as well.

**Comment by anders9ustafsson** [comment]
@deyung Will you be able to provide a more comprehensive list of storage UIDs?

**Comment by deyung** [comment]
Yes, I’ll work on it. I’m not family with the M4 process but I’ll figure something out to import that entire list.

**Comment by anders9ustafsson** [comment]
For inspiration, you might want to take a look at how I generated a new table of anonymization rules in the recent PR #595. It shouldn't be too difficult to use a similar approach for parsing the UID table in the HTML file. But I think it would be good to first check with the *dcm4chee* folks that they are OK with us using their data.

**Comment by deyung** [comment]
Not a problem, I’ll dig into it.

**Comment by gofal** [comment]
Will close this due to inactivity. If there are any updates, you are welcome to reopen it again.

**Pull request closed without merging**
