### PR TITLE
Issue #675 - GetMinMax

### LINKED ISSUE #675: GetMinMax
https://github.com/fo-dicom/fo-dicom/blob/9d2e8339b3549a8db307efa3cb127c4cc1709836/DICOM/Imaging/Render/PixelData.cs#L704

Hi,

I noticed one issue with the 'GetMinMax' function.  If by chance you have a dataset where all the pixels are the same value and they are equal to the padding value provided, then it will return double.MaxValue / double.MinValue as the range.  I think this can be corrected as follows:

```

public DicomRange<double> GetMinMax(int padding)
{
     // null or empty return a MinMax of 0/0
      if (Data == null || Data.Length == 0)
                return default(DicomRange<double>);

    // set to the first value to start
      var min = Data[0];
      var max = Data[0];
      var data = Data;
      var length = data.Length;

// loop thru the rest of the pixels, updating the min/max if a new min/max is found
      for (var i = 1; i < length; i++)
       {
           var value = data[i];
           if (value == padding) continue;
                if (value > max)  max = value;
           else if (value < min) min = value;
        }
    return new DicomRange<double>(min, max);
}
```

Best Regards,
Jamie

### PR DESCRIPTION
**Pull request by jwbruce93**
Fixes #675 GetMinMax
 If by chance you have a dataset where all the pixels are the same value and they are equal to the padding value provided, then it will return double.MaxValue / double.MinValue as the range.

Fix: 
-if pixel data null or empty return a MinMax of 0/0
-else set to the first value to start
-loop thru the remaining items in the array, updating min/max if found

### CODE REVIEW

**Comment by gofal** [comment]
Thanks for the pull request. But you have to be carefull. The return of 0 as max or min does not distinguish any more between there are really pixels of value 0 or there is no data other than paddingvalue. 
Its the same if - as described in bug #675 - there is a image that is cleared and all pixels are of value paddingvalue, then there are no valid min and max pixels, because the padding value has to be ignored.
Take a look for example at https://github.com/fo-dicom/fo-dicom/blob/1d871c3b5f321b770e8780cdbee1ae68a2eb8896/DICOM/Imaging/GrayscaleRenderOptions.cs#L208. The GetMinMax is required to find rendering options and there the GrayscaleRenderOptions relies on Double.MaxValue or double.MinValue to obtain if there are valid min or max values. 
Your change brakes this code and might break some users implementation.

**Comment by jwbruce93** [comment]
Thanks for the quick feedback.  So is this the expected behavior for the following scenarios?

**Data is null or length 0**
Return Double.MaxValue and Double.MinValue to indicate there is no valid min/max

**Every pixel has the same value (e.g. a black image)**
both min and max are the value of the first pixel (Data[0]) ? 

**Any other dataset (e.g. a valid image)**
min is the smallest value in 'Data' and max is the largest value in Data

**Comment by gofal** [comment]
That's to be discussed. Returning Double.MaxValue or DoubleMinValue to indicate invalid data is of course some kind of hack or workaround. 

The current implementation makes no difference between case 1 (data is null or length 0) and case 2 (black image). So I understand your wish to distinguish here. But always returning a value and therefore hide the cases 1 and 2 as here in the pull request is not fine either.

The method is internally used to find a default windowing. And there the pixel values equal to paddingvalue shall be ignored. So if the whole image only contains of pixel that are equal to paddingvalue then from this point of view there is no valid min and max. I don't know what your intention is to get the main and max including the paddingvalue.
So an idea could be to add an parameter `bool skipPaddingValue`. if true then the padding values are skippend the the current behaviour can be used from 'GrayscaleRenderOptions', and if the parameter is false then you will get your desired value?
Or extend the class `DicomRange<T>` by a property `Valid` that is set to false in case 1 and 2 and set to true in case 3, while min and max are filled in case 2 as you described. Then `GraysacleRenderOptions` evaluates the DicomRange.Valid property while you just evaluate the min and max value ignoring the Valid-Property.
Or any other ideas?

**Comment by Cregganbane** [comment]
Hi my 2c, 
Previously:
1) Return the range of values in an image not equal to the padding value
2) If there are no such values return (min: +X,max: -X)

The proposal changes this to 
1) Return the range of values in an image not equal to the padding value unless the first pixel is the padding value, in that case return the smallest range of the padding value and the min,max of all other pixels not equal to the padding value. 

It's not uncommon for modalities to set, for example, the area outside the cylindrical CT acquisition region to the padding value usually including the first pixel. Meaning you will get a completely different min,max. Given the point of this code is to return a range to construct a default WW/WL over this would be wrong. 

It is important to know when there is no pixel without the padding value but that is unambiguous in the original code - just compare range.Min > range.Max. This is a very common construction in range classes and usually done in a method/property range.Empty or some such. 

If you need to see if everything is the padding value then check range.Empty && Data.Length > 0?

**Comment by gofal** [comment]
With the last commit the interface IPixelData now has 2 overloads of GetMinMax. One has the padding value as parameter and calculates the DicomRange as before. The other has no parameter and does not skip the padding value, thus returns the padding value if the image is empty and only contains the padding value.
While the windowing class calls GetMinMax with the padding value, jwbruce93 could call the method without the parameter.
Please evaluate.

**Pull request merged**
