### PR TITLE
Pr/added editorconfig

### PR DESCRIPTION
**Pull request by MacL3an**
Cudos to Rickard H. for initiating this. We suggest we add a editorconfig-file so we ensure we get the same formatting from different ppl.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@MacL3an For this configuration file to "do" anything, you need to install the EditorConfig VS extension, right?

**Comment by MacL3an** [comment]
Correct. Sorry, I forgot to mention that detail :).

On 5 February 2016 at 16:11, Anders Gustafsson <notifications@github.com>
wrote:

> @MacL3an <https://github.com/MacL3an> For this configuration file to "do"
> anything, you need to install the EditorConfig VS extension, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fo-dicom/fo-dicom/pull/215#issuecomment-180394760>.
>



-- 
Håkan Angus MacLean
Sweden: +46 72 542 0505
E-mail: hakan@maclean.se

**Comment by anders9ustafsson** [comment]
@MacL3an Is this config file fully in sync with the conventions that are currently used in the *fo-dicom* code?

**Comment by MacL3an** [comment]
I can't guarantee that it is fully in sync, but from the files I've opened
this seems to match. I've mainly looked at the tabs (4 spaces as tabs).
/Håkan

On 8 February 2016 at 09:36, Anders Gustafsson <notifications@github.com>
wrote:

> @MacL3an <https://github.com/MacL3an> Is this config file fully in sync
> with the conventions that are currently used in the *fo-dicom* code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fo-dicom/fo-dicom/pull/215#issuecomment-181255457>.
>



-- 
Håkan Angus MacLean
Sweden: +46 72 542 0505
E-mail: hakan@maclean.se

**Comment by anders9ustafsson** [comment]
@MacL3an OK, thanks! Will pull soon.

**Pull request merged**
