### PR TITLE
Serilog logging adapter cleanup. Connects to #8

### PR DESCRIPTION
**Pull request by IanYates**
- Added constructor override to the SerilogManager so the global Serilog.Log instance can be used OR a specific ILogger instance can be used
- Renamed the SerilogLogger class to SerilogLoggerAdapter to make its intent more clear
- Made the namespace Dicom.Log rather than DICOM.Log so that it is more consistent with the rest of fo-dicom.  Since this hasn't yet been made public it's not a breaking change.  The NLog one has not been touched.  If we wanted to change it then it might be worth doing so before release.
- Created a simple example project

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@IanYates I am still confused with the implementation of the `GetLogger` override in `SerilogManager`. Shouldn't `GetLogger` use the private `ILogger` field if it exists, and only use the global `Log` class when `SerilogManager` is instantiated with the parameter-less constructor?

In my interpretation, I would change the implementation of `SerilogManager` as follows:

    // Parameter-less constructor
    public SerilogManager() {
        _serilogLogger = Serilog.Log.Logger;
    }

    // GetLogger override
    public override Logger GetLogger(string name) {
        var serilogLogger = _serilogLogger.ForContext("fo-dicom", name);
        return new SerilogLoggerAdapter(serilogLogger);
    }

Or is there something that I am misunderstanding in the *Serilog* details?

**Comment by IanYates** [comment]
@anders9ustafsson - no, you're not missing anything.  VS crashed on me a couple of times and a completely mucked up my Git work at one stage.  I redid everything but not quite correctly :(  I'll fix that now

**Comment by IanYates** [comment]
Fixed.  Thanks for reviewing.

**Comment by IanYates** [comment]
The demo output, run once with the global logger and once with the alternate constructor that has some extra logging context applied.

seq output

**Comment by IanYates** [comment]
Dang - GitHub edit error...  Fixing now

**Comment by anders9ustafsson** [comment]
Great, thanks Ian. I'll merge this PR, and I will make a NuGet pre-release of *fo-dicom.Serilog* within the next few days.
When you have the time, can you also write a developer's wiki page explaining how to format log messages in *fo-dicom*, *Serilog* style?

**Pull request merged**
