### PR TITLE
Fix for #645 - frame size is calculated wrong in case of uncompressed YBR_FULL_422 images

### LINKED ISSUE #645: Problem rendering multiframe image
### Expected behavior
Image is rendered correctly (even if there are errors in IOD) as in microDicom or Offis Toolkit.

### Actual behavior
Images are rendered wrong (first frame ok, then the offset seems to become calculated wrong so the output looks strange).

### Steps to reproduce the behavior
Create DicomImage object from attached DCM and create System.Drawing.Bitmap of it and display them or store them in file system.

### fo-dicom version and OS/platform
Win 10 Pro 64-Bit, .NET 4.5.2, fo-dicom v3.1.0-alpha / 3.0.2 (both versions affected)
[PixelDataError.zip](https://github.com/fo-dicom/fo-dicom/files/1535813/PixelDataError.zip)

### PR DESCRIPTION
**Pull request by WernMich**
Fixes #645 

See [http://dicom.nema.org/... YBR_FULL_422 -> 2. Note](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.3.html#sect_C.7.6.3.1.2)

> Though the chrominance channels are downsampled, there are still nominally three channels, hence Samples per Pixel (0028,0002) has a value of 3, not 2. I.e., for pixel data in a Native (uncompressed) format, the Value Length of Pixel Data (7FE0,0010) is not:
> 
> Rows (0028,0010) * Columns (0028,0011) * Number of Frames (0028,0008) * Samples per Pixel (0028,0002) * (⌊(Bits Allocated (0028,0100)-1)/8⌋+1)
> 
> padded to an even length, as it would otherwise be, but rather is:
> 
> Rows (0028,0010) * Columns (0028,0011) * Number of Frames (0028,0008) * 2 * (⌊(Bits Allocated (0028,0100)-1)/8⌋+1)
> 
> padded to an even length.

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] ~~I have updated API documentation~~
- [X] I have included unit tests
- [X] I have updated the change log:
- [X] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- fixed calculation of frame size in case of uncompressed YBR_FULL_422 images

### CODE REVIEW

**Comment by amoerie** [comment]
Hi @WernMich and thank you for providing a fix! Is there any chance you have a sample DCM file that demonstrates this problem? 
Ideally, we could use this file in a unit test that verifies your modification fixes the issue. 

If not, I wouldn't consider it a blocker, but it would definitely be nice to have.

**Comment by WernMich** [comment]
Hi, I attached a sample in the first post of issue #645. 




Best, 


Michael




Get Outlook for Android







On Mon, Aug 3, 2020 at 10:42 AM +0200, "Alexander Moerman" <notifications@github.com> wrote:















Hi @WernMich and thank you for providing a fix! Is there any chance you have a sample DCM file that demonstrates this problem?

Ideally, we could use this file in a unit test that verifies your modification fixes the issue.


If not, I wouldn't consider it a blocker, but it would definitely be nice to have.

**Comment by amoerie** [comment]
Hi @WernMich I've created a PR against your branch here: https://github.com/WernMich/fo-dicom/pull/1 

This will 

- merge the latest development branch into your fork
- fix any conflicts
- add the same fix in the v5 code
- add missing tests in both the v4 and the v5 code

When you accept that PR, I will accept this one. 

Thanks!

**Comment by amoerie** [comment]
The CI is a bit of a mess right now, there's a separate issue for that. Merging this!

**Pull request merged**
