### PR TITLE
Added check for existing SourceAET when constructing DicomFileMetaInfo

### PR DESCRIPTION
**Pull request by nodonnell**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Where SourceApplicationEntityTitle already exists in a DICOM dataset or DICOM file meta information, the DicomFileMetaInformation constructor will now use this, instead of generating a new Source AET from the machine name on Save() calls.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@nodonnell Many thanks for contributing. Will review this and get back to you as soon as possible.

**Comment by gofal** [comment]
DicomTag 0002,0016 Source Application Entity Title is of type 3, meaning it is optional. It shall contain the AETitle of the one who last wrote or modified the dataset. So generally always taking the one that already is contained is not a good strategy.
I could not find a issue describing the reason why to do this. Why is this better?

**Comment by nodonnell** [comment]
Thanks for the reply.

Currently, the machine name is always used as the Source AET - this may not always be appropriate; forcing the machine name as Source AET rather than allowing an implementation to specify a Source AET is necessary allows a DICOM implementation. 

Where a Source AET is not provided, it seems appropriate to default to the machine name. However, individual machines may act as AEs in different contexts, and allowing for configuration of the Source AET written to a DICOM file facilitates this configuration.

Another implementation of this may be an overload of `CreateSourceApplicationEntityTitle()` which takes a string argument `candidateAET` or similar, and makes sure it's suitable for writing to the DICOM file as Source AET. If this is preferable, I will happily change the implementation to account for a pre-configured Source AET in this way.

**Comment by gofal** [comment]
I see, that is a very good point.
But overriding the method would not be so easy since this method lives in class DicomFileMetaInformation, from which you can derive, but this class is constructed internally in DicomFile...

What do you think of a public static property called SourceAET or similar. This property could live in the class Setup or in class DicomFile. it should be somewhere more obvious than in DicomFileMetaInformation. on starting the application as an initialization you set a value to this property. And CreateSourceApplicationEntityTitle takes this if it has been set and the Machinenname otherwise. 
What do you think?

**Comment by Cregganbane** [comment]
Fo-dicom should not use the computer name for the source AET, its potentially identifiable information and further nothing to do with tag semantics. Since its type 3 why not just skip it since its very easy to add this before serialization outside of fo-dicom?

**Comment by gofal** [comment]
I had merge-conflicts with this pull request, because it also includes some changes from Anders Gustafsson concerning Unity Network. So I did cherry-pick with the commits of nodonnell directly into the development branch, and close this pull request.

**Pull request closed without merging**
