### PR TITLE
Check milestount count vs sequence depth before resetting state. Connected to #178 and #184

### PR DESCRIPTION
**Pull request by anders9ustafsson**
Same fix should also solve #184.
Please review.

### CODE REVIEW

**Comment by Ed55** [comment]
@anders9ustafsson Strange. I think source.MilestonesCount > this.sequenceDepth is correct.
When I am using source.MilestonesCount >= this.sequenceDepth I cannot e.g. parse the example provided by nicco66 for case #184.
I need to check if this is related to the CP-246 'fix' code I have still in.
Unfortunately I cannot do this today anymore. Will come back to you asap.

**Comment by Ed55** [comment]
@anders9ustafsson Got a spare hour :-) and I had a look into #64 again.
#64 is a "CP-246" case as well, the instance is explicit, the private UN tag internally is coded implicit.

For my understanding you can fix #184 with source.MilestonesCount > this.sequenceDepth but it seems you cannot fix #64 without a solution for the "CP-246" #177 as well?

The hour is gone :-( I will follow this up ...

**Comment by aerik** [comment]
sorry, what's cp-246?

**Comment by Ed55** [comment]
@aerik See ftp://medical.nema.org/medical/dicom/final/cp246_ft.pdf 
Short Story: values with VR UN shall be interpretated as ILE, regardless of the datasets transfer syntax.
And see #177

**Comment by anders9ustafsson** [comment]
@Ed55 OK, for cleanliness I will reject this PR, then first fix #177 and finally re-post a PR for #178 with your solution in it. Have you made any further modifications locally to fix CP-246, or is the solution you have outlined in #177 still relevant?

**Comment by Ed55** [comment]
@anders9ustafsson I haven't made any more changes until now.

**Pull request closed without merging**
