### PR TITLE
Change to .net standard fo-dicom.Json

### PR DESCRIPTION
**Pull request by javier-alvarez**
Fixes # .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/4.0* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Update DICOM.Json to .netstandard1.3 from PCL (deprecated)
- Update DICOM.Test.Desktop to 4.6 minimum required to be compatible with netstandard1.3

### CODE REVIEW

**Comment by javier-alvarez** [comment]
@anders9ustafsson it looks like the build doesn't do nuget restore correctly for .netcore2.0. Is it possible to update the nuget version used or make sure we use dotnet restore?

**Comment by mia-san** [comment]
thank you for pull-request.

well, current DICOM.NetCore package is targeted to .net standard 1.3
do we have to change that to 2.0?

also, do we need to upgrade .net 4.5.2 projecto to 4.6.2 ?

**Comment by javier-alvarez** [comment]
@mia-san I have reverted those changes to the minimum. I still need to upgrade the DICOM.Tests.Desktop to 4.6 from 4.5.2 as it is incompatible with netstandard1.3

Is this ok? What are the next steps?

**Comment by javier-alvarez** [comment]
@mia-san I don't understand why the build is failing in DICOM.Dump I haven't changed that project or its dependencies

**Comment by mia-san** [comment]
I've just cloned your branch and DICOM.Dump builds fine.
what is your build error ?

**Comment by javier-alvarez** [comment]
@mia-san https://ci.appveyor.com/project/anders9ustafsson/fo-dicom/builds/21829417

**Comment by mia-san** [comment]
hmm, it seems CI server is trying to build DICOM.Dump program for .netcore.
I'm not a expert of this CI things and I don't know if this is supposed to succeed, probably something on CI server  is not right.

btw, would you sync your branch against fo-dicom/development, not fo-dicom/4.0 ?

**Comment by javier-alvarez** [comment]
@mia-san I could not build locally the fo-dicom/development branch. I got some error saying that some file was missing

**Comment by mia-san** [comment]
hmm, I was successfully build fo-dicom/development branch by re-targeting.
would you try that?

**Comment by javier-alvarez** [comment]
I have done the retargeting to development

**Comment by javier-alvarez** [comment]
I cannot build locally DICOM.Full.sln and it also fails in the CI check. Any ideas?

**Comment by mia-san** [comment]
hmm, strange.

besides CI error, I've just finished rebuilding DICOM.Full solution by re-targeting freshly checkout fo-dicom/development on VS2017(15.9.5) in all configuration(Debug/Release, AnyCPU/ARM/x64/x86).

retarget dialog says:
Windows SDK version:
  10.0.17763.0,
toolset version:
 v141
projects:
..\Universal\libijg8.Universal.vcxproj,
..\Universal\libijg12.Universal.vcxproj,
..\Universal\libijg16.Universal.vcxproj,
..\Universal\DICOM.Native.Universal.vcxproj,
..\Desktop\libijg8.x64.vcxproj,
..\Desktop\libijg8.x86.vcxproj,
..\Desktop\libijg12.x64.vcxproj,
..\Desktop\libijg12.x86.vcxproj,
..\Desktop\libijg16.x64.vcxproj,
..\Desktop\libijg16.x86.vcxproj,
..\Desktop\DICOM.Native.vcxproj,
..\Desktop\DICOM.Native64.vcxproj

**Comment by javier-alvarez** [comment]
The build keeps failing. I have managed to build locally now by doing what you suggested

**Comment by javier-alvarez** [comment]
Ok I will revert that. Do you need anything else from me?

**Comment by mia-san** [comment]
although project owner may have other opinions, current state looks fine to me.
wait for pull-request gets merged...

thank you!

**Comment by gofal** [comment]
Tried some things on AppVeyor but didn't manage to make it build. Local build works fine, so it is obvious an issue there.
Althought you changes are fine, I don't like to have the project without CI.

Thats why I reverted it for now and continue investigating.

As soon as I found a solution I will merge this again.

**Pull request merged**
