### PR TITLE
IAsyncEnumerable

### LINKED ISSUE #1037: Consider IAsyncEnumerable in IAsyncDicomC*Provider
Some `IAsyncDicomC*Provider`-s, specifically `CMove`, `CFind` and `CGet` currently return `Task<IEnumerable<Task<DicomC*Response>>>`. This type doesn't actually enable completely async enumeration of those responses - once the first `Task` is ready, the `IEnumerable` already needs to be ready, and know e.g. the number of responses that will be provided.

The idiomatic type for this type of async enumeration is `IAsyncEnumerable`, which is part of the standard library since the .NET Standard 2.1 and .NET Core 3 targets, and is available for other targets via `Ix.Net` https://github.com/dotnet/reactive . Would it be possible to switch to them / add another interface using them? Converting from the previous types to those types can be done automatically be some helper method (this in C#8 syntax, older syntax requires some more boilerplate):
```csharp
async IAsyncEnumerable<T> Convert<T>(Task<IEnumerable<Task<T>>> task)
{
    var iter = await task;
    foreach (Task<T> t in iter)
    {
        yield return await t;
    }
}
```

Converting the other way around is not always possible - except by awaiting the entire `IAsyncEnumerable` on the first task. It is for those cases, where the responses are coming one-by-one, that the new interface will be useful.
```csharp
async Task<IEnumerable<Task<T>>> Convert<T>(IAsyncEnumerable<T> iter)
{
    var l = new List<Task<T>>;
    await foreach (T t in iter)
    {
        l.Add(Task.FromResult(t));
    }
    return l;
}
```

Edit:
I can draft a PR for this, if this is acceptable (I guess someone else should choose the names for the new interfaces ;) ).

### PR DESCRIPTION
**Pull request by amosonn**
Fixes #1037.

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [X] I have updated the change log
- [X] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Switch to IAsyncEnumerator on netstandard2.1, netcoreapp3.X

Do note that this is a BREAKING CHANGE for users of these targets; perhaps it would be better to make this a minor-version switch (i.e. 4.1.0 instead of 4.0.6)?

### CODE REVIEW

**Comment by amoerie** [comment]
Hey, thanks for creating this PR! 

I see that you've updated both the network code for fo-dicom 4.0 ( DICOM/Network/DicomService.cs ) and the network code for fo-dicom 5.0 ( FO-DICOM.Core/Network/DicomService.cs )

Since fo-dicom 5.0 is the way forward and is built on top of .NET Standard 2.0, I think it might be best if we only implemented this in the 5.0 branch.

You can think of fo-dicom 4.0 as going into maintenance mode, just like .NET framework is being treated by Microsoft.  Taking that into account, I would revert the changes for fo-dicom 4.0.

The only downside, that I can see, is that you will have to wait for the next preview release of 5.0 before you can use these changes.

What are your thoughts on this @gofal ?

**Comment by amosonn** [comment]
Ah, I was wondering what was the difference between DICOM and FO-DICOM.Core, I thought maybe the last one was targeting netcore, but I didn't realize that it was supposed to be for fo-dicom 5.0. Isn't it better to manage this in a separate branch, rather than alongside in a different folder?

Anyway, just to make sure: fo-dicom 5.0 is switching to netstandard2.0, and has nothing to do with dotnet5, right? As you can tell from my first commit above, I'm not on windows :), so this whole framework-to-standard thing is a bit lost on me, I'm using netcore. Does the switch mean that fo-dicom won't be using .NET Framework-specific features anymore, and the same imaging features will be available on netcore as well?

**Comment by gofal** [comment]
Yes. A big goal in fo-dicom has alwys been to support as many systems as possible. So it started as portable (PCL) project. With PCL it was impossible to do certain things (networking, IO, imaging), so there have been this several platform specific projects. NetStandard now allows to bring it back into one codebase for many platforms again! So we do not want to build for the latest/newest platforms, but we want to use stable settled widely supported platform (I hope I was able to express my thoughts). See #870 for the discussion about that.

Yes. with fo-dicom 5.0 (built in netstandard 2.0) there will only be one project with no platform specific code. For Imaging you still have to choose one of the 2 nuget-packages: fo-dicom.ImageSharp or fo-dicom.Drawing. First one is also netstandard and should in my opinion be the default imaging library, but many users are working with windows and therefore would use fo-dicom.Drawing to have System.Drawing.Bitmap support.
And for codec: in fo-dicom 4.0 only windows was fully supported. Now with fo-dicom 5.0 we promote to use the codec from Efferent, which works on windows, linux and soon Mac. (https://github.com/Efferent-Health/fo-dicom.Codecs/issues/6). Sadly this is currently paused due to corona, but I hope it will continue soon.

**Comment by amosonn** [comment]
Does this mean it got merged for both 4.x and 5.x? I haven't had the time yet to strip the changes away from 4.x.

**Comment by amoerie** [comment]
I was thinking the same thing. We can still create a new PR that strips the
changes for 4.x

Op vr 26 jun. 2020 15:01 schreef amosonn <notifications@github.com>:

**Comment by gofal** [comment]
this is currently only included in version 5.0

I am currently heavily testing with codec in 5.0. Efferent published their version for fo-dicom 5.0
So you could wait some days and then use 5.0?

**Comment by amoerie** [comment]
No @gofal, I believe you misunderstand me.

I mean that this PR made changes to both DICOM/Network/DicomService.cs and  to FO-DICOM.Core/Network/DicomService.cs, do you see?

image

The intent was to revert all changes in DICOM/Network because we will only have IAsyncEnumerable in fo-dicom 5.0, but you already merged this PR now.

We should make a new PR that reverts the changes in the 4.0.x line.

**Comment by gofal** [comment]
oh sorry, i thought you had it ready. I will revert the changes in 4.0 directly....

**Pull request merged**
