### PR TITLE
take advantage of new feature in C#8.0: using declaration

### PR DESCRIPTION
**Pull request by MaherJendoubi**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Leveraged the use of enhanced using declarations
- Upgraded LangVersion to C#8.0 for FO-DICOM.Benchmark
- Upgraded LangVersion to C#8.0 for FO-DICOM.Imaging.Desktop

### CODE REVIEW

**Comment by amoerie** [comment]
Hi! Can we talk about this? I'm actually not the biggest fan personally of this new using syntax, because it makes the scope in which it lives less explicit and it can actually cause issues when there are multiple disposables being used in one method.

I don't really see the value yet.

**Comment by gofal** [comment]
Agree that it is not always good. You see a unit test is failing where the stream to a file has to be closed/disposed first before the file can be opened again for reading. There the scope of the open stream has to end explicitly.

But there are many functions, where the scope does not matter, where it it just important that the resource is disposed soon and not just anytime when the GC does it. There reducing one level of indent improves the readability of the code.

**Comment by MaherJendoubi** [comment]
Thank you for your great feedback! I share the same feeling.
The failed tests make me think twice before using this feature. I am trying to grasp the value through learning by doing.
For the moment, it is mainly the code visibility: no more brackets and indentations. I find the 2 following links that deserve reading :
https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/using.md
https://github.com/dotnet/csharplang/issues/2948

**Comment by amoerie** [comment]
> But there are many functions, where the scope does not matter, where it it just important that the resource is disposed soon and not just anytime when the GC does it. There reducing one level of indent improves the readability of the code.

I believe the GC does not automatically dispose of objects for you. It only calls the destructors. It's always better to dispose the object yourself, AFAIK. And disposal is important, because it releases native Windows handles in a lot of cases. Just wanted to mention this for clarity. I know it's outside the scope of this discussion. 🙂

I'm fine with limited use of the new using syntax, only for simple scenarios, by the way. 

@MaherJendoubi can you make sure the tests are green?

**Comment by MaherJendoubi** [comment]
@amoerie The local tests are green but still an issue with the first build / v4-net-framework. Please review.

**Comment by MaherJendoubi** [comment]
@amoerie @gofal Should we keep the development for the .NET framework?

**Comment by MaherJendoubi** [comment]
Lifecycle-Graphic

**Comment by amoerie** [comment]
> @amoerie The local tests are green but still an issue with the first build / v4-net-framework. Please review.
> 
> image

For the v5 release of fo-dicom, we made a new copy of the code that we started changing. The purpose of this is that we plan to support v4 with security and patch fixes for the foreseeable future, and that v5 will be the way forward for .NET Core.

Try opening DICOM.Desktop.sln or DICOM.Full.sln and fix any compilation errors please :-)

**Comment by amoerie** [comment]
> @amoerie @gofal Should we keep the development for the .NET framework?

Yes. A lot of consumers of fo-dicom are still on .NET Framework and cannot migrate away for possibly years to come. 
We will maintain - but only maintain - v4 for another long while.

**Comment by MaherJendoubi** [comment]
> Try opening DICOM.Desktop.sln or DICOM.Full.sln and fix any compilation errors please :-)

image

**Comment by amoerie** [comment]
> > Try opening DICOM.Desktop.sln or DICOM.Full.sln and fix any compilation errors please :-)
> 
> image

This simply means you do not have the correct Windows SDK version installed (can be installed via Visual Studio installer)
I reverted your commit that changed these SDK versions (to something you did have locally, I presume) because updating these values is a breaking change.

**Comment by amoerie** [comment]
@MaherJendoubi I fixed up a few things and CI is green now.

The only thing I don't really like is that you seemed to have randomly upgraded some nuget packages in several places.
I'm not against this, but can you do this in a separate PR? And I haven't checked this, but did you update these packages in all projects, or just in the ones that you passed by? I don't want multiple versions of dependencies in the same solution.

**Comment by MaherJendoubi** [comment]
@amoerie Thank you for the great help. My bad, I should use another PR for updating the NuGet packages. Those packages concern only the .NET Core version : (FO-DICOM.Core.csproj, FO-DICOM.NLog.csproj, FO-DICOM.Imaging.ImageSharp.csproj, FO-DICOM.Json.csproj, FO-DICOM.Benchmark.csproj and FO-DICOM.Tests.csproj).

**Review by amoerie — APPROVED** [review]

**Comment by amoerie** [comment]
Looks good to me, I'll let @gofal have the final say :-)

**Pull request merged**
