### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by MaherJendoubi**
#### Changes proposed in this pull request:
- <s>Concensus --> Consensus</s>
- orignalDicom --> originalDicom
- wether --> whether

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@gofal Please review.

**Comment by MaherJendoubi** [comment]
@gofal I am not sure about the T4 changes because I ignore how it works.

**Comment by gofal** [comment]
Thanks a lot!
English wording and orthography is something difficult for me, I am happy you care about that!

The "Concensus" wording in the UIDs is something that has to be that way. The T4 generated stuff are data that are downloaded from DICOM Standard homepage dicom.nema.org. From that the UIDs, Codes, Keyword etc are generated and should not be changed.
See here http://dicom.nema.org/medical/dicom/current/output/chtml/part06/chapter_A.html. When you search for the uid "1.2.840.10008.6.1.1140" on the page you will find that the name of this UID is defined as "concensus". We have to use it, even if it is a misspelling.

**Comment by MaherJendoubi** [comment]
@gofal thanks a lot for the review! I reverted the changes for "concensus".

**Pull request merged**
