### PR TITLE
Public setters on RootQueryRetrieveInfoMove and StudyRootQueryRetrieveInfo. Connected to #304

### LINKED ISSUE #304: RootQueryRetrieveInfoMove and StudyRootQueryRetrieveInfo need public setters

### PR DESCRIPTION
**Pull request by zcr01**

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@zcr01 Just so I understand the rationale; there already are public constructors where these properties are set. Why do you need the ability to modify them?

Personally I am a little bit reluctant switching to mutable types, but if there is a good motivation I have no problems being pragmatic :-)

**Comment by zcr01** [comment]
As part of handling an A-ASSOCIATE request, the SCP (if supporting extended negotiation), is supposed to check the sub-items, and return 1 for each accepted proposal or 0 for each rejected proposal (or for each proposal the client doesn't support).  (see: http://dicom.nema.org/medical/DICOM/2014a/output/chtml/part04/sect_C.5.html)

As far as I can tell, the implementer of IDicomServiceProvider.OnReceiveAssociationRequest() is supposed to call SendAssociationAccept() on the passed in DicomAssociation to complete the request, which would mean these negotiation sub-items need to be modifiable to accept or reject proposals.

**Comment by anders9ustafsson** [comment]
OK, thanks. Please update the API documentation accordingly, i.e. *Gets __or sets__*.

**Comment by zcr01** [comment]
Done.

**Comment by anders9ustafsson** [comment]
Sorry, but I couldn't sleep over this (well, more or less). I am still not convinced: why can't you just create a new object in *OnReceiveAssociationRequest* and pass the new object forward instead?

Could you give a code example where it is undoubtedly better to modify the properties of the existing object rather than create a new object?

**Comment by IanYates** [comment]
IMHO, if we can keep immutability then we should.  It helps with future-proofing as we can more readily assume things won't change whilst some code is executing.

**Comment by anders9ustafsson** [comment]
@zcr01 After looking over the unit test [here](https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Network/PDUTest.cs) I am ready to agree with you; it *does* make sense to have public setters for these negotiation sub-items after all. Just needed to digest it :-) 

Will pull the PR later today. Thanks again!

**Pull request merged**
