### PR TITLE
Logging refactoring

### PR DESCRIPTION
**Pull request by IanYates**
Moves NLog dependency outside of fo-DICOM and updated fo-DICOM to take advantage of more advanced logging frameworks (although a lot more could be done on this front that what's in this PR).

* Created 2x new projects - DICOM.NLog and DICOM.Serilog
* Each logging project will auto-wire itself into fo-DICOM.  The expectation is that none or one of these logging assemblies will be in your project.
* Created an adapter to take Serilog-style log messages and let them be morphed into NLog-style messages.  Added tests for this including edge-cases (invoking such edge cases really indicates a problem in the fo-DICOM code invoking the logger but it's good to handle, or at least define, weird behaviour).
* Updated fo-DICOM so that it uses named arguments for logging rather than positional arguments.
* Updated fo-DICOM so that, in several places where it logs an error, it doesn't just append exception.ToString() on to the log format.

I appreciate that this PR looks HUGE - it really isn't.  Just step through each of the commits and you'll see the incremental changes.

This PR is based on using .NET v4 projects.  The .NET v4.5 upgrade PR will need to be adjusted to include these two new projects OR we create an extra PR afterwards to fix these two projects.

### CODE REVIEW

**Comment by IanYates** [comment]
Further refactoring would include
* Using Logging Contexts (see https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext)
* More use of structured data output (see https://github.com/serilog/serilog/wiki/Structured-Data)
This can be done in a fashion that supports multiple loggers

**Comment by anders9ustafsson** [comment]
@IanYates I merged the .NET 4.5 request just now, since there were no objections to it. If you want to, I can make the necessary upgrades of the new projects, once they have been merged.

I will look more closely into your pull request within the next few days.

**Comment by IanYates** [comment]
No problem :)  Thanks!

**Comment by anders9ustafsson** [comment]
> * Updated fo-DICOM so that it uses named arguments for logging rather than positional arguments.

Correct me if I am wrong, but this is a C# 6 construct, right? Which will require VS 2015? Are we ready for that jump?

**Comment by IanYates** [comment]
Poor wording on my part...

When using a logging server, such as Seq (http://getseq.net), you can get better insight into your logs, etc if what you log has descriptive names - so it's {user} instead of {0} and so on.

See https://getseq.atlassian.net/wiki/display/SEQ10/Logging+to+Seq+with+Serilog for an example of using Serilog to send stuff to Seq server.  Other people use Serilog to send to CouchDB, Mongo, ElasticSearch, SQL Server, flat text, Loggly, etc.

NLog, and other older logging frameworks, expect {0} instead of {name}.  There's an adapter function included that does that translation automatically (that's what has all of the units tests around it since it's the actual new bit that's not just plumbing).

So those wanting to keep on with NLog, Log4Net, etc can still have a ready-made logging adapter and those using some of the newer frameworks, like Serilog, can get extra functionality too.

**Comment by IanYates** [comment]
Which is a really long way of saying "it's not a C# thing" :)_

**Comment by IanYates** [comment]
Actually, this blog post demonstrates the benefits nicely - http://nblumhardt.com/2015/01/give-your-instrumentation-some-love-in-2015/

**Comment by anders9ustafsson** [comment]
Thanks for the clarification, Ian. One question that pops up regarding the adapter (haven't scanned all unit tests yet, maybe you already have this covered):

What if the order of named arguments in the format string differs from the order of the arguments? For example,

    log.Error("This is wrong, message: {errorMessage}, code: {errorCode}", code, message);

**Comment by anders9ustafsson** [comment]
Another thing that I noticed in the *DICOM.sln* file, is that you have re-added the *Mixed Platforms* configuration when you added the new logging projects. I know, it's VS that "behaves badly". Nevertheless, it would be good if you could remove the *Mixed Platforms* configuration from the solution so that we have a unequivocal path for building.

**Comment by IanYates** [comment]
It doesn't know you've got them back to front so it'll just log as is.  That'd be similar to the (possibly confusing due to deliberate out of order arguments)
`log.Error("This is wrong, message: {1}, code: {0}", code, message)`

There is talk of the library support C# 6.0 string interpolation but, as you said, that is a way off and is only of benefit if the local variable name happens to match the descriptive property name for logging purposes anyway.

As for mixed platforms, I can remove that.  Now that fo-DICOM is up to .NET 4.5 I might as well rebase the PR from there too.  Will do so later.  Any other feedback is most welcome.

**Comment by anders9ustafsson** [comment]
Thanks, Ian, for these clarifications. It all looks very good, I just needed to understand how it all works.

**Comment by anders9ustafsson** [comment]
@IanYates As far as I can see, you have not made use of the `NameFormatToPositionalFormat` method in [`ConsoleLogger`](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Log/ConsoleLogger.cs). For completeness, this is necessary too, right?

Is performance an issue? For example, if the logger is inside a large loop, the string conversion of the *Serilog*-style message templates will be repeated unnecessarily. 

Since C# 6 will offer a similar solution via string interpolation, could it be an option to leave the `{0}` format style as it is for the time being, and instead implement a converter for *Serilog* where it picks up the argument names via reflection and insert them in the format string prior to making the *Serilog* call? (I have not verified that reflection manages this scenario; if it doesn't, then I need to rethink my suggestion.)

I noticed that the *Serilog* expert is reluctant to using string interpolation in [Serilog](http://nblumhardt.com/2015/01/c-6-string-interpolation-and-serilog/). Still, for many other logging libraries I could expect that converting [message templates](https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-syntax) may become a performance bottleneck. Or am I overly pessimistic? What do you think?

**Comment by IanYates** [comment]
@anders9ustafsson - you're right about the console logger.  I'll fix that.

Nick is reluctant to use string interpolation, mainly (IIRC) because he feels that the local variable name often doesn't make for a good field name in the log  (example "d" versus "document" or even "documentToProcess").  Having said that, I suspect that when C# 6 becomes more mainstream then string interpolation will probably end up being supported somehow.

Your concerns about performance are fair.  It occurs to me that the log string templates are pretty much static - they'll always convert to the same thing.  Would you be against me putting a simple dictionary (wrapped with a quick lock, or perhaps just use concurrent dictionary) in to avoid the repeated conversions?

I can't see a way to pick up the argument names via reflection.  If the parameters were given via expressions, where the expression could both be compiled/evaluated AND be pulled apart to get the property accessor, then maybe.  But that'd be slow too.  The dictionary ought to make this issue go away but I'm happy to listen and discuss if you think otherwise.

Of note, I believe the new ASP.Net logging framework (it's name escapes my memory at the moment) uses a format similar to Serilog.

**Comment by anders9ustafsson** [comment]
@IanYates Yes, giving some more serious thought about a *Serilog* converter using reflection, I realize now that this is unrealistic, if not impossible.

I don't think it is worthwhile to add more complexity by storing the conversions in a dictionary either. It still adds overload to the logger call, although hopefully dictionary lookup is less costly than the string morphing. Furthermore, what if some format strings are defined dynamically, for example? The dictionary could then potentially grow very big. No, better to keep the solution as simple as possible, and do the conversion in every call.

I am OK with this change. However, it might be a good idea to for example write up a wiki page to explain the principles and limitations of these message templates for non-*Serilog* users, both for us *fo-dicom* developers, but also for consumers of the libraries who may potentially take advantage of the logging mechanism from *fo-dicom* in their own code. What naming rules are there, for example? Is it possible to use any character in a named parameter, or?

**Comment by IanYates** [comment]
Good points.

Ideally, if logging is being done well, the string format should NOT be defined dynamically - but that's a whole other debate (http://nblumhardt.com/2014/09/how-not-to-parameterize-serilog-events/)  :)

I can write a wiki page.  There isn't any wiki at all at the moment - before I start I've opened an issue #24 for feedback about wiki structure.

**Comment by anders9ustafsson** [comment]
@IanYates @hdesouky If you want me to, I can pull this request within the next few days, and subsequently make the solution cleanup, new project upgrade to 4.5 and update `ConsoleLogger`, as previously discussed above. Should I pull, or is there something anyone would like to add first?

**Comment by anders9ustafsson** [comment]
@IanYates I have now merged this PR, but there is one thing that concerns me: how are the `Init` classes in the *DICOM.NLog* and *DICOM.Serilog* assemblies supposed to work? The classes are declared `internal`, so they cannot be reached from other assemblies. The class source code only consists of a static constructor, which will be run only if the class is instantiated, but as far as I can see it never is.

Am I missing something central? Is *Serilog* using some reflection "trick" to invoke an `Init` class if it exists, or? If that is the case, I don't think the same approach applies to *NLog*?

**Comment by IanYates** [comment]
@anders9ustafsson - apologies for the radio silence the past few days on this.  

Let me double check and I'll open a new PR to resolve some of these issues we'd discussed, plus the static constructor issue you mentioned (I thought such constructors were executed on assembly load, but I think you're right about them only being guaranteed to at least execute before the first instance of the class is created).  

The init classes were meant as a convenience which I was thinking of taking out anyway as they could cause trouble for end users writing unit tests anyway (they may want a plain console logger, or no logger at all, rather than what their main application is doing for logging)

**Comment by anders9ustafsson** [comment]
@IanYates Just so you know, I made the following clean-ups after having merged your PR:

* Upgraded *Dicom.NLog* and *Dicom.Serilog* projects to .NET 4.5
* Removed unused references from *Dicom.NLog* and *Dicom.Serilog* projects
* Removed *Mixed Platforms* configuration from solution.
* Upgraded *NLog* *NuGet* package version to latest stable (3.2.1) for all *NLog* dependent applications
* Implemented conversion of log message to positional format in `ConsoleLogger`

I have not done anything with the `Init` classes, so that issue remains.

**Comment by IanYates** [comment]
@anders9ustafsson  - thank you for taking care of that for me.  More to come this weekend.

**Pull request merged**
