### PR TITLE
Add extra encodings for .NET Core (#481)

### LINKED ISSUE #481: DicomFile.Open  with file encoded by GB18030 fails in .NET Core
### Expected behavior
Using DicomFile.Open on a file with GB18030 encoding in the .NET core should not fail.

### Actual behavior
Fails with:

'GB18030' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.\nParameter name: name", Source: "Dicom.Core", StackTrace: "   at Dicom.DicomFile.Open(IFileReference file, Encoding fallbackEncoding)\n   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext()", TargetSite: "Dicom.DicomFile Open(Dicom.IO.IFileReference, System.Text.Encoding)", _typeTag: "DicomFileException"}

### Steps to reproduce the behavior

Use DicomFile.Open to open a file with GB18030 encoding

### fo-dicom version and OS/platform
3.0.1 Windows 10 x64

### Commentary
When running under .NET Core (for any app, not just fo-dicom), GB18030 encoding is not included by default. This can be demonstrated by a simple .NET Core console app:

```
namespace TestEncoding
{
    class Program
    {
        static void Main(string[] args)
        {
            //Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); //uncomment this line to include GB18030 encoding, make sure you also reference System.Text.CodePages Nuget Package
            var enc= Encoding.GetEncoding("GB18030");
            Console.WriteLine("It worked");
            Console.ReadLine();
        }
    }
}
```
This program runs fine under the full .NET framework but fails under .NET Core.

The fix is to add the System.Text.CodePages package and call 
```Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);```
This will add additional encodings, including GB18030

### Potential Fix

Add System.Text.CodePages NuGet package to the DICOM.NetCore project and add a static constructor for DicomEncoding with a conditional compilation for NETSTANDARD that calls ```Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);``` 

### Current Workaround

Add System.Text.CodePages NuGet package to your program that consumes fo-dicom and call Encoding.RegisterProvider while bootstrapping.

### Further action

I'm happy to create a pull request that registers the provider in a static constructor for DICOMEncoding, but before I did, I wanted to make sure the proposed fix is agreeable. I love unit tests, but not sure if one would add much value here.

### PR DESCRIPTION
**Pull request by npnelson**
Fixes #481.

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [X] I have updated the change log
- [X] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
Added static constructor in DICOMEncoding to load extra encodings not included by default in .NET Core

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
Great work, @npnelson! Many thanks!

I took the liberty to make some minor changes, I hope you do not disapprove.

* Even though it is not always avoidable, I would like to use as few compiler directives as possible in the shared code. Since the `DesktopIOManager` acts as both the .NET Framework and .NET Core I/O manager implementation, and since the `IOManager` already provides the default encoding, I also moved the code pages registration to the `DesktopIOManager` static constructor.
* As much as possible, I would like to reuse the unit tests from .NET Framework in .NET Core. Therefore I have removed the .NET Core specific unit test class you added, and instead added as a link `DicomEncodingTest` from the desktop unit tests into .NET Core unit tests. Regardless, I don´t see the issue you were facing with the `actual`/ `expected` order, the unit tests pass both on .NET Framework and .NET Core.

**Comment by npnelson** [comment]
Yes, I agree that your implementation is an improvement.

However, if you run the ```GetEncoding_GB18030_Desktop()``` test ***individually*** in .NET Core, it fails. The reason is ```var expected = Encoding.GetEncoding("GB18030").CodePage;``` fails because ```Encoding.RegisterProvider...``` is not called in the test harness (and doing so would not allow us to test the system since it is a static registration). However, when run with other tests, it is likely that the ```Encoding.RegisterProvider``` codepath is hit in the Desktop.IOManager, in which case, the ```var expected = Encoding.GetEncoding("GB18030").CodePage;``` succeeds.

One could make the argument that the test is of limited value and could be removed.

**Comment by anders9ustafsson** [comment]
OK, now I get it. Thanks!

But maybe the test should be reformulated then? What we really want to test is that the GB18030 encoding is sufficiently assigned, i.e. that the assignment does not throw. So the test could rather be:

    int codePage;
    var exception = Record.Exception(() => { codePage = DicomEncoding.GetEncoding("GB18030").CodePage });
    Assert.Null(exception);
    Assert.Equal(54936, codePage);

Do you agree? I am not saying that we need to change the test right away, but eventually it could be refactored, I think.

**Comment by npnelson** [comment]
Yes, that would be a much better test. I should have thought of that. I'm happy to do a PR with that (but you did all the work!) Just let me know. I enjoy helping out where I can. You and the other contributors have built a nice library.

**Comment by anders9ustafsson** [comment]
@npnelson It is great if you can provide a PR with this update! And many thanks for your kind words about *fo-dicom*.

**Pull request merged**
