### PR TITLE
Fix Null Reference Exception on cloning to Jpeg Process2_4

### PR DESCRIPTION
**Pull request by paul81**
Fixes # .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Experienced a Null Reference Exception when cloning a DICOM file to Jpeg Process2_4 when parameters were not being defined although the method defaulted to null.
- Changed handling of parameters when setting photometric interpretation to set to YBR_Full when the parameters are null.

### CODE REVIEW

**Comment by paul81** [comment]
Should have checked issues first but looks like this potentially addresses issue #889 .

**Comment by amoerie** [comment]
LGTM! 👍 

@paul81 would you be willing to resolve the merge conflicts in the changelog?

**Comment by paul81** [comment]
No worries. Should be fixed now and is pending check completion.

**Comment by amoerie** [comment]
Great, thanks. Now all you need is approval from @gofal 😉

**Pull request merged**
