### PR TITLE
Codec loading - add logging and default the search filter wildcard. Connected to #40

### PR DESCRIPTION
**Pull request by IanYates**
* Logging is done at the debug level to indicate which folder & filter is being searched for codecs.
* A warning log message is generated if no codecs are loaded.
* The creation of the DirectoryCatalog has a try/catch wrapped around it.  The exception is logged.  Currently it is also rethrown (so no external behaviour change is evident)
* If no search filter for filenames is provided, it is defaulted to Dicom.Native*.dll

I made these changes in my local fork whilst debugging #40

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@IanYates In principle I am fine with this PR, but I am not sure about the necessity to internally set the `search` variable to `Dicom.Native*.dll` if it is `null` on entry? The same search pattern is used already in the static constructor, which would be run first anyway. Do you really need to explicitly call `LoadCodecs` with default/`null``search` argument?

**Comment by IanYates** [comment]
Fair point on the static constructor.  As mentioned elsewhere, I deliberately keep the codecs out of the bin folder of my web app since that causes other issues.  Because of that they're also not found by that static constructor's call so I need to call LoadCodecs manually.  Having a sensible default made sense.
Would it be OK to change the static constructor instead?

Out of curiousity, has anyone ever written a custom codec for fo-dicom?

**Comment by anders9ustafsson** [comment]
OK, if we change the static constructor to call LoadCodecs with no arguments, we will avoid duplicity of the DLL search pattern. I would be fine with this. 

I don't know of any third-party codec implementations, but I guess it would be reasonable to implement MPEG codecs as separate DLLs, for example?

**Comment by anders9ustafsson** [comment]
@IanYates Unless you object, I will pull this PR in a short while (< 1/2 hour), and update the static constructor at the same time.

**Comment by IanYates** [comment]
@anders9ustafsson  - thanks!

**Pull request merged**
