### PR TITLE
Raysearch/dicom status bugs. Connected to #499

### PR DESCRIPTION
**Pull request by rickardraysearch**
Fixes a bug in DicomStatus and adds support for adding new known DicomStatuses.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
Many thanks, @rickardraysearch, for this PR. Could you add some background explaining the rationale for the bug fix? Also, generally I'd prefer PR:s against the *development* branch. Is there any specific reason for including it in the *3.0* branch?

**Comment by rickardraysearch** [comment]
I created a bug for this as well, #499 . 

This PR also adds support for adding more known statuses. We need this for UPS statuses ( http://dicom.nema.org/medical/dicom/current/output/html/part04.html#sect_CC.2.1.4 ) but also for custom warnings and errors.

**Comment by rickardraysearch** [comment]
Ah, sorry about the targeting. I'll move it to the development branch.

**Comment by anders9ustafsson** [comment]
If you consider it critical, it is OK if you leave it on the 3.0 branch at this time.

**Comment by rickardraysearch** [comment]
Brilliant, thanks! I think that this is the last issue preventing us from getting back on mainline fo-dicom.

**Pull request merged**
