### PR TITLE
added sample for Wado

### PR DESCRIPTION
**Pull request by do0om**
I added a sample of a partial wado implementation using Web Api, I saw you were talking about it in  #127. Hope this can help.
I am open to criticism and suggestions.

I don't know why VS added Mixed Platforms configurations in .sln files, do you guys have the same problem?

### CODE REVIEW

**Comment by IanYates** [comment]
Thanks!  I haven't checked it out yet - first day back at work.  However the 'mixed platforms' bit happened to me too last time I did things with the projects.  No big deal to clean up :)

**Comment by anders9ustafsson** [comment]
@do0om Many thanks for providing this example. I haven't looked it over yet, but I think it is a very welcome addition to the existing samples.

Regarding the addition of the *Mixed Platforms* configuration, that is an artifact in VS 2013 when adding or removing projects to a solution containing for example C/C++ projects. It would be great if you could add a commit where you have removed the *Mixed Platforms* configuration (using the Configuration Manager).

**Comment by anders9ustafsson** [comment]
@do0om Many thanks for removing the *Mixed Platforms* configuration, it will simplify the upcoming merge considerably. Do you also have access to VS 2015? In that case, it would be wonderful if you could add the *Wado* project to the *DICOM.Full* solution (*Examples* folder) as well. Otherwise, or if adding the project is causing you any problems, don't bother, I'll add it myself as part of the merge.

@IanYates @do0om The PR is not making any modifications to *fo-dicom*'s distribution code, but there is still quite a big change in the set of consumed *NuGet* packages. To really be on the safe side, I would prefer to hold the merge of this PR until after the release of 2.0 (which should be very close now). Does anyone of you have problems with this?

**Comment by do0om** [comment]
@anders9ustafsson Sorry, I don't have VS 2015 yet.

And no problem for holding the merge.

**Comment by IanYates** [comment]
No problem with leaving until after 2.0.  Makes sense.

**Comment by anders9ustafsson** [comment]
@do0om I have now tried this out and it is indeed an interesting example. Once again, many thanks for contributing.

However, since there is not yet any WADO support built-in the *fo-dicom* libraries, I am thinking that this sample would be a little misplaced. Right now, my gut feeling is that it would be better to use your sample as a basis and inspiration for the (expected) class library implementation.

My recommendation would thus be to close this PR now. When we later on start implementing web services support we may use code from this PR to implement WADO support directly in the class library/ies.

What do you think?

@IanYates and others interested: do you agree with my conclusion, or would you prefer that we *do* pull this PR in already now?

**Comment by do0om** [comment]
I understand that this could be a little misplaced, but it's not completely off topic either : it's using fo-dicom under the hood.

I think if someone looking for a wado starting project checks fo-dicom, he probably won't check a closed pull request and won't see anything related to Wado. This could be a waste of time reimplementing Wado again.

Anyway, once you implement wado as a class library, the example will be gone.
But in the meantime, this can help someone and encourage to use fo-dicom.
That's just my two cents. I won't be offended if you don't pull it in ;), the decision is up to you.

**Comment by anders9ustafsson** [comment]
@do0om OK, makes sense. You may have convinced me to reconsider my standpoint :-)
@IanYates What do you think?

**Comment by IanYates** [comment]
Since we have an fo-dicom GitHub org, maybe we start making separate repositories within the org for this sort of thing. It has worked really well for other popular oss libraries (eg Serilog and its many sinks and enhancers). That way the example is quite easy to discover but is still separate from, and can evolve alongside, the main repo.

Make sense?

**Comment by do0om** [comment]
It makes sense, the only problem is that, in this case, the other repository would be temporary since you will eventually have the class library implementation.

**Comment by anders9ustafsson** [comment]
@IanYates Sounds like a splendid idea to me!
@do0om I see your concern; we would then have to be observant to make sure that the repositories stay in sync with each other. We should be able to manage that, though.

Based on Ian's proposal, my suggestion is that I create a new repository *fo-dicom-samples* in which we can place good ideas like this one. I also suggest that we in the *fo-dicom-samples* solution use *NuGet* to access the *fo-dicom* libraries, to limit the direct dependencies between the main and the samples repository.

I can add the *Wado* sample as the first project in the samples solution.

Any thoughts on this?

**Comment by do0om** [comment]
Great idea to gather samples in a separate solution.

**Comment by anders9ustafsson** [comment]
And there we go!

Repository [fo-dicom-samples](https://github.com/fo-dicom/fo-dicom-samples) created, WADO sample added.

Many thanks for contributing, @do0om !

**Pull request closed without merging**
