### PR TITLE
Fix Frame Caching in DicomImage

### LINKED ISSUE #805: RenderImage() returns the wrong image for MultiFrame DicomImage
### Expected behavior
Using a parallel loop to call `RenderImage()` on the set of frameIndexes for a MultiFrame DicomItem causes `RenderImage()` to return the correct image for the frameIndex passed

### Actual behavior
When a parallel loop is used to call `RenderImage()` on a set of frameIndexes, the frames will often have some misplaced images in the set. 

### Steps to reproduce the behavior
Use a parallel loop to call `RenderImage()` on a set of frameIndexes. To test that it was `RenderImage()` causing the problem, I burned the frameIndex used to retrieve each image into the image as soon as it was returned. While the frameIndexes were in order, the actual images were obviously not correctly ordered, leading me to believe that `RenderImage()` is returning the wrong image sometimes when used in parallel.

```
Parallel.For(0, _dicomImage.NumberOfFrames,
    frameIndex =>
    {
        var frame = CreateBitmap(frameIndex);
        
        lock (this._cachedImages)
        {
            this._cachedImages[frameIndex] = frame;
        }
    });
```

```
private BitmapSource CreateBitmap(int frameIndex)
{
    using (var result = this._dicomImage?.RenderImage(frameIndex))
    {
        var resizedResult = result.AsWriteableBitmap().Resize((Int32)ImageWidth, (Int32)ImageHeight, WriteableBitmapExtensions.Interpolation.Bilinear);

        DrawText(resizedResult, (frameIndex + 1).ToString(), 25);
    }
}

```
To be clear, this exact code runs perfectly if a regular for loop is used in place of the parallel loop.

### fo-dicom version and OS/platform
fo-dicom 4.0.0 / WPF

### PR DESCRIPTION
**Pull request by CDarbonne**
Fixes #805 

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [ ] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
-Updated Frame Caching in DicomImage to working version for multi-threading issues
-Added try-catch recursive failsafe in RenderImage()
-Fix two misc. spelling errors in ILUT.cs summaries

### CODE REVIEW

**Comment by gofal** [comment]
Thanks for the pull request.
I would like to discuss it. Becaus now the pixeldata is cached internally without the user knowing it or giving him the possibility to turn it off. So the pixeldata is doubled in memory always even if the user does not need it.
maybe adding a boolean property to turn it off? Or by adding a method  "DicomFrame DicomImage.GetFrame()" to return a explicit class, that the user can hold in its own collection to cache the data explicitly? If your viewing-application has the list of DicomFrames loaded, then you could dispose the originial multiframe-bytearray to save lots of memory. 
Just some thoughts, what do you think? Am I too afraid?

**Comment by CDarbonne** [comment]
Hmmm... I'm not sure, to be honest. Our application is a viewer and thus should always cache the images for performance purposes. I have not noticed a significant increase in memory consumption, but maybe we haven't run into a set large enough to see it, or we haven't had a function that was impeded by the memory size. I don't see a downside to putting in a boolean option to turn caching off though. I can go ahead and do that if that's the course of action you want to take. I think that would be a better idea than forcing the caching to be done on a higher level via a DicomFrames class.

**Comment by CDarbonne** [comment]
Also, now that 4.0.1 has been released, should I put the changes in the changelog under 4.0.2?

**Comment by gofal** [comment]
Yes, the release notes should be added under "4.0.2 (TBD)".

**Comment by gofal** [comment]
So you did not notice any more memory consumption? the pixel data should have been doubled. But right, if you only show small amount of images in your viewer then this is neglible compared to the memory consumption of the application /framework/...
But I think of cases where my customers had multiframes: Ultrasound (rather small images) and radiography (a kind of video while the patient swallows some contrast liquor) and there you have several houndret MB. If you double it that is not so fine. 

And yes, introducing a new class just for caching is something overdesigned. It would be more usefull and acceptable for the user if this new class does offer more functionality and convenience functions to the user than just the caching thing. 

adding a property (and for backwards compatibility reasons setting it by default to False) would be the simplest solution for now?

**Comment by CDarbonne** [comment]
I did notice a slight increase, but it was not significant so I feel like I'm not able to give a good opinion of whether or not it would be an issue. I think your expertise is what to rely on in this case. I think you are right that it should have the additional property and keep the Dicom Frame in mind for the future if more functionality is required. I did already implement a default to false property in there and I will upload the changes along with the change log corrected tomorrow when I get back to my desk!

**Comment by CDarbonne** [comment]
@gofal The changes have been pushed, let me know if anything else needs to be updated or changed!

**Comment by gofal** [comment]
Sorry for being annoying, but just took a look at the code and you did fix the issue that the wrong image is returned and you cache the image, but you also broke your original intention to run the method in parallel.

You wanted to speed up your application and cal RenderImage in a ```Parallel.For``` loop. But now the current code has a huge ``` lock (_lock)``` around nearly the whole RenderImage body. This makes your Parallel.For run just the same as a regular for. 

The locking is only required where you modify class fields or access fields that can be modified.

**Comment by gofal** [comment]
.. And in method RenderImage now the evaluation of the field ```_rerender``` is missing. If you cache the pixel data into the directory and then change the property ```Scale``` then the pixeldata has to be recreated (interpolating etc). but the current code always returns the cached pixeldata. So even if the parameter tells to used the cached image, if _renderer is true, then the pixeldata should be recreated.

**Comment by gofal** [comment]
right after I have sent the last comment I realized that evaluating _renderer will not be enough. For example if cou call RenderImage for the first 2 frames. then you change the Scale from 1.0 to 1.5 and call RenderImage for the first frame again. then the cached pixeldata of frame 1 is scaled with 1.5 and the pixelddata of frame 2 is still with scale 1.0. When the next RenderImage is called you have to remember the scale of the cached IPixelData and compare if you have to recreate the IPixelData. 

This all was no issue as long as DicomImage only held the recently rendered IPixelData as cache and in case any property (frame, scale) changed it was recalculated.

Now we have to store more information with the IPixelData. 

And now the property ```CurrentFrame``` can be removed completely. Since it was only to remember which frame the field _pixels contained. And with this the constructor-parameter ```frame``` also is obsolete.

**Comment by CDarbonne** [comment]
Not annoying at all! This is a bit of a learning experience for me so I appreciate the help!

I see what you mean about the lock. I didn't think that I added that much to the existing lock, but looking at it now I can see that it doesn't make a lot of sense for that much to be in there. 

As far as the rerender goes, if I add a scale property to IPixelData that is set on `Rescale(double scale)` and simply compare it with the DicomImage scale when a cached image is pulled to test if a rerender is necessary, do you think that will be sufficient?

In regards to the constructor-parameter `frame`, should the functionality of partly initialized states be preserved in some way after removing the parameter?

**Comment by gofal** [comment]
I think, that will be sufficient, to compare the scale-property when fetching the cached pixel data.

I am not sure what you mean by partly initialized states in the construcotr. The other properties as the initial _scale or _dataset or _pixeldata have still to be initialized.

**Pull request closed without merging**
