### PR TITLE
Made ClassUID and Version fields readonly. Fixes #52

### LINKED ISSUE #52: DicomImplementation public fields should be readonly
Currently, the `ClassUID` and `Version` fields in the `DicomImplementation` class are mutable, which could potentially have unwanted consequences. To overcome this issue, the fields should be declared `readonly`.

### PR DESCRIPTION
**Pull request by anders9ustafsson**
Please review.

### CODE REVIEW

**Comment by hdesouky** [comment]
Make sense

**Comment by hdesouky** [comment]
but if someone doesn't have the source code and want to specify his own implementation class uid and version he needs to recompile!

**Comment by anders9ustafsson** [comment]
@hdesouky You are absolutely right, I was a little quick when posting this issue and PR. I will revert the `readonly` declaration for the `ClassUID` field but keep it for `Version`. OK?

**Comment by anders9ustafsson** [comment]
As discussed also in PR #45, we should eventually consider to implement a more flexible initialization configuration of the library. But not for this release, though :-)

**Comment by anders9ustafsson** [comment]
On second thoughts, I'll reject this PR altogether. Let's focus on an improved library initialization in a future release instead.

**Pull request closed without merging**
