### PR TITLE
Update DICOM dictionary to version 2015c

### PR DESCRIPTION
**Pull request by anders9ustafsson**
Dictionary can successfully be updated to version 2015c.

@IanYates @hdesouky @GMZ please give advice whether you think it is OK to include this update this late in the release process of 1.1.0.

### CODE REVIEW

**Comment by IanYates** [comment]
@anders9ustafsson - I don't have a problem with it.  Thanks for taking the time to update the dictionaries and create the PR.  
The only breaking change that I can see is the shift from IEC6127 to IEC61217.  I won't even pretend to know what that's about but if it's going to be a breaking change we might as well take it now rather than pushing out an official release and then having a breaking change arrive afterwards.

**Comment by anders9ustafsson** [comment]
Good point regarding the breaking change. Thanks, Ian.

**Comment by GMZ** [comment]
@IanYates , @anders9ustafsson, @hdesouky IEC6127 to IEC61217 isn't a breaking change, its a correction of a typo, see http://dicom.nema.org/medical/dicom/current/output/pdf/releasenotes_2015c.pdf, page 4, 3.16 this should be fine to merge

**Comment by anders9ustafsson** [comment]
Thanks for the clarification, Chris. I haven't checked, but maybe the 60217 UIDs were not in the 2011 dictionary anyway, and then there will be no backward compatibility issues at all if we use the 2015c dictionary.

**Comment by IanYates** [comment]
@GMZ - figured it was something like that.  The "breaking" bit was more about someone, somehow, already taking a dependency on the name in their code.  I suppose it wouldn't have worked anyway, and since it was new to the spec, probably no one encountered it in the wild.  Thanks for the clarification :)

**Pull request merged**
