### PR TITLE
DICOM client rewrite

### PR DESCRIPTION
**Pull request by amoerie**
This is a PR containing my DICOM client rewrite

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Rewrite DICOM client internals using state pattern, making the entire flow a lot more robust
- Provide coherent support for cancellation using cancellation token
- new DicomClient can live side by side with the old DicomClient because it lives under a new namespace, to maintain backwards compatibility for consumers. This makes the new DicomClient "opt-in", for now.

### CODE REVIEW

**Comment by amoerie** [comment]
The tests are green (huzzah!).
I've duplicated all DicomClient related tests so they are run on both the old and the new DICOM client.

There are a few things left on my TODO list:

- Introduce locking during DICOM client state transitions. In the current implementation, it is possible that an event happens (e.g. a DICOM abort) that is received right in the middle of a state transition. In that case, the event is lost. Any events during state transitions should be buffered and passed to the new state immediately after the transition has completed.

- Add support for C-Store requests, just like the old DICOM client. I've simply not done this yet.

-

**Comment by amoerie** [comment]
Transition locking is done now. This means any events (OnAbort, OnDisconnect, OnSendQueueEmpty) will always propagate to the most correct, current event, even when there is a state transition happening right at the same moment. I've used SemaphoreSlim for this, because unlike 'lock' (aka the backing Monitor class) SemaphoreSlim has proper async support.

I'm torn if I even want to include support for WaitForAssociationAsync in this new API, it feels a bit silly to have a new API that immediately has an Obsolete method. What are your thoughts on this, @gofal ?

**Comment by gofal** [comment]
If you support WaitForAssociationAsync, then this does not have to be deprecated any more. Take a look at issue #605 . The Method WaitForAssociation was deprecated because there was no usefull usecase and events could handle this better.
Now, if you have SendAsync working properly then there might be a useful usecase.

The new DicomClient already has some breaking changes, so there is no need to implement each and every method the old DicomClient offered. If it makes sense, then implement it, if it does not, then leave it. That are my thoughts on this. 

Many thanks for digging so much into this DicomClient class!

**Comment by amoerie** [comment]
No problem at all, it was actually quite fun to rewrite! :-) 

Ah, that linked issue explains a lot. It does make little sense to have it, so I'll remove it. The association events (and the state events) should be more than sufficient to handle each scenario. And it will always fail if you've not triggered an association request indeed.

If I may ask one further question, do you happen to know the purpose of having specific C-Store request handling in the old DICOM client? I'm wondering what the use case is, to decide whether I should add support here too.

**Comment by gofal** [comment]
Of course. The C-Store request handling is implemented in case of C-Get.
Usually a dicomclient is a "simple" client, eg, it sends requests and receives some responses. Except in case of C-Get, there the server is asked to send a dicom file to the client via the same association (in contrast to c-move there the file shall be sent via a separate association to a store scp). Of course the dicomclient could just take the DicomResponse object and extract the dicom file, but the extra handling of c-store request simplifies this.

**Comment by amoerie** [comment]
This might be a stupid question, but shouldn't this be a callback on the DicomCGetRequest object then?

**Comment by gofal** [comment]
I'm not sure about it. I was not involved when the decision was made why the event lives in DicomClient and not in DicomCGetRequest. When I think about it, the only reason I can imagine is, that if you send two CGetRequests to the server then you get some CStoreRequests returned. It could be hard to decide to which of those two CGetRequests the CStoreRequest belongs.

**Comment by amoerie** [comment]
The abort behavior and send behavior seems to be stable now. The only thing that's still missing is the OnCStoreRequest support for CGet requests.

**Comment by amoerie** [comment]
It also seems I inadvertently modified some config in some places, e.g. adding a dependency to ValueTuple in DICOM.Desktop. Writing that down here so I don't forget to investigate if that's really necessary, because I believe I removed all usages of tuples.

**Comment by gofal** [comment]
Agree. The reference to System.ValueTuple in dicom.desktop.csproj would not mind, but since the code also has to compile in other projects, so the reference will not be necessary.

You also set the  LangVersion explicit to 7.0, for some reason I dont know
and in dicom.shared.shproj there is a option TargetFrameworkVersion set to v4.0, this is propably not necessary, too.

**Comment by amoerie** [comment]
@gofal as mentioned on gitter, I think this rewrite is mostly completed.

The OnCStoreRequest support has been added, including a unit test.

I have been thinking about the AbortAsync API though, and I have a few issues with it:

- Unlike the cancellation token that you can pass into SendAsync, AbortAsync is another external method call on the DicomClient surface. This means that AbortAsync can sometimes be "too late", e.g. when you abort during the request of an association, some requests might be sent anyway because the abort signal does not propagate fast enough.

- This affects the unit tests too, the abort unit tests have been a bit flaky because it depends on the performance characteristics of the machine whether the abort will happen fast or slow.

Instead of an AbortAsync method, there is actually another approach we could take here: make the cancellation behavior of the DicomClient configurable. Right now, the new DicomClient will always cancel gracefully, which means that it will stop sending requests, release the association and wait for that to complete, then close the connection.

I imagine we could add a "CancellationMode" parameter to DicomClient.SendAsync, which is an enum, and which would have the following options:

- WaitForSentRequestsToCompleteAndThenReleaseAssociation
- DoNotWaitForSentRequestsToCompleteAndImmediatelyReleaseAssociation
- ImmediatelyAbortAssociation

The way that it's implemented now, DicomClient will use approach # 2 "DoNotWaitForSentRequestsToCompleteAndImmediatelyReleaseAssociation" when the cancellation token is marked as CancellationRequested, and will use approach # 3 when AbortAsync is called.

I believe it would be an improvement however if we extended the signature of SendAsync with this CancellationMode, giving the caller the responsibility to choose the algorithm.

In return, I would remove the AbortAsync API.

**Comment by amoerie** [comment]
@gofal Another important question: is it possible to upgrade the .NET Framework version to at least 4.6? This introduces a new enum member TaskCreationOptions.RunContinuationsAsynchronously which helps avoid deadlock problems. See https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcreationoptions

**Comment by gofal** [comment]
the Microsoft-link, you provided, says:
Applies to
.NET Core
3.0 Preview 5 2.2 2.1 2.0 1.1 1.0
.NET Framework
4.8 4.7.2 4.7.1 4.7 4.6.2 4.6.1 4.6 4.5.2 4.5.1 4.5 4.0
.NET Standard
2.1 Preview 2.0 1.6 1.4 1.3 1.2 1.1 1.0
UWP
10.0
Xamarin.Android
7.1
Xamarin.iOS
10.8
Xamarin.Mac
3.0

So current Framework verion should be fine. Please be aware, that the code currently has to copile for all projects: dicom.desktop, dicom.portable, dicom.core, ...

**Comment by amoerie** [comment]
Actually the enum member TaskCreationOptions.RunContinuationsAsynchronously has been introduced in .NET Framework 4.6.2..
The other options already existed, like you say.

**Comment by amoerie** [comment]
@gofal We could probably upgrade any frameworks in a separate PR. I add a a pragma check to see if we have access to .NET Standard, so if we upgrade the version in the future, the enum usage should light up automatically.

If and when you have the chance to code review my PR, I am eager to hear your final feedback. As far as I'm concerned, this new DicomClient is ready for prime time.

One last thing: if you skipped past my previous comment about AbortAsync, I did end up removing the AbortAsync API in favor of adding a cancellation mode. It makes *a lot* more sense and ended up making the unit tests a lot more reliable too.

**Comment by amoerie** [comment]
Some notes on my last commits:

- Since AddRequest is used in the "sending requests" and "lingering" states, it needed to be encapsulated in the state transition lock to avoid racing conditions. Because the locking mechanism is built on SemaphoreSlim.WaitAsync, and because we want to avoid sync over async at all times, I refactored AddRequest into AddRequestAsync. In most cases, this method can complete synchronously anyway, so I imagine the overhead will be minimal.

- Since AddRequest now locks internally, it's probably inefficient to call this 1000 times if you have 1000 requests. Instead of acquiring and releasing the Semaphore 1000 times, it would be better to just lock once, enqueue all 1000 requests and then release the lock. This is exactly what AddRequestsAsync does, which accepts an IEnumerable of DicomRequest.

**Comment by amoerie** [comment]
For science, I compared the performance characteristics of the old and the new DICOM client, and it looks like there should be some room for optimization still. These are the results for sending 1000 C-Echo requests:

Method | Mean | Error | StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated
-- | -- | -- | -- | -- | -- | -- | --
NewDicomClient_SendEchos | 360.0 ms | 7.167 ms | 12.55 ms | 9000.0000 | 2000.0000 | - | 30.16 MB
OldDicomClient_SendEchos | 371.2 ms | 7.459 ms | 13.45 ms | 8000.0000 | 2000.0000 | - | 29.93 MB

As you can see, both perform quite comparably in terms of speed and memory usage. The new DICOM client consumes slightly more memory but uses that to work a little bit faster.

Now that we have the tools to measure this, this opens up opportunities to optimize this in the future.

**Comment by gofal** [comment]
Great job! There are still some commits. You suggest me to merge this and you create a new new pull request, or would you recommend still to wait some time before merging?

**Comment by amoerie** [comment]
Your timing is impeccable. 👌 I am actually dealing with another deadlock
that I've found, but when the tests are green again then you can merge the
request, yes please! 🙏

**Comment by amoerie** [comment]
I'll try to summarize what kept me working these past few days on this PR:

Sometimes, a unit test that tries to send 1000 requests would fail with the message that only 300 requests were actually sent. 

See these builds: 
- https://ci.appveyor.com/project/anders9ustafsson/fo-dicom/builds/24750625/tests
- https://ci.appveyor.com/project/gofal/fo-dicom/builds/24752393

The changes that triggered those builds were trivial, so I knew something was still wrong with the implementation. After some hunting I found out that DicomService.OnSendQueueEmpty can be triggered in certain hard-to-replay scenarios, which causes the DicomClient to believe its work is done, causing the tests to fail.

To work around this unfortunate behavior, without severely modifying how DicomService works, I added pending request tracking to the DicomClientSendingRequestsState, so it would know with 100% certainty whether its requests have all completed or not.

Furthermore, I discovered that the transition locking mechanism in DicomClient had potential deadlocks, because we would trigger events from within the transition lock, which again could cause more events, resulting in a deadlock. 

See these builds:
- https://ci.appveyor.com/project/gofal/fo-dicom/builds/24758509
- https://ci.appveyor.com/project/anders9ustafsson/fo-dicom/builds/24759301
- https://ci.appveyor.com/project/anders9ustafsson/fo-dicom/builds/24759555

These all timed out because of Tasks that never complete, or deadlocks.

To solve this, the following modifications were made:

- Avoid parallel communication with DicomClientConnection. Make sure there's always only one task actually sending requests, preventing too many concurrent events.
- Extract some logic out of the locks, such as AddRequest and OnSendQueueEmpty. These methods, should they happen 'too late' (i.e. when a state is already transitioning away to another) carry no consequences for the eventual result.
- Get rid of "out-of-band" request sending (e.g. via Task.Factory.StartNew), and instead make the "send more requests" mechanism a first class citizen of the transition flow.

I believe the new DICOM client is now in a very solid state, and I am verifying none of its unit tests are flaky anymore.

**Comment by amoerie** [comment]
P.S. The tests that are now failing are completely unrelated, I’ve made an issue for them here: #868

**Comment by amoerie** [comment]
Couldn't resist some final refactorings. 😄 I'll stop now!

**Pull request merged**
