### PR TITLE
Fix opening a DICOM file from a stream

### LINKED ISSUE #1264: FellowOakDicom 5.0.1 - Invalid DICOM files are produced when the initial DicomFile is opened from a stream
**Describe the bug**
DICOM file is corrupt/unreadable when DicomFile.Save is called after creating that DicomFile from a stream

**To Reproduce**
DicomFile.Open(a stream)
DicomFile.Save(a path)
Trying to open the resulting DICOM file fails

**Expected behavior**
The DICOM file should be valid

**Environment**
Fellow Oak DICOM version: 5.0.1

### PR DESCRIPTION
**Pull request by amoerie**
Fixes #1264 .

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Fix issue in StreamByteBuffer that causes an error when opening a DICOM file from a stream

### CODE REVIEW

**Comment by amoerie** [comment]
I had some troubles reproducing the original issue, but I found a unit test that demonstrates the issue:

When opening a DICOM file from a Stream with FileReadOption.Default or FileReadOption.ReadLargeOnDemand, the StreamByteBuffer will write too much data.

Now, Fellow Oak DICOM actually correctly reads this file and just adds a gibberish DicomTag at the end. 
One might question if we should throw an error here. dcmdump definitely does:

image

I will leave the tests running for a few minutes, and then push the fix too.

**Comment by amoerie** [comment]
As you can see the test fails now because the last DICOM tag is not identical, when you open from a path or from a stream:

```
[xUnit.net 00:00:03.60]     FellowOakDicom.Tests.Bugs.GH1264.OpenDicomFileFromStream [FAIL]
  Failed FellowOakDicom.Tests.Bugs.GH1264.OpenDicomFileFromStream [479 ms]
  Error Message:
   Assert.Equal() Failure
Expected: (7fe0,0010)
Actual:   (fffe,e000)
  Stack Trace:
     at FellowOakDicom.Tests.Bugs.GH1264.OpenDicomFileFromStream() in D:\a\fo-dicom\fo-dicom\Tests\FO-DICOM.Tests\Bugs\GH1264.cs:line 48
```

**Comment by amoerie** [comment]
@gofal This is now ready for review and fixes the issue described in #1264

**Comment by gofal** [comment]
is this issue with the additional 0-value at the end now solved, or is it still included here?

**Comment by gofal** [comment]
My assumption: there was this method in EvenLengthBuffer, that previously wrote the stream and filled with 0-values until the desired length is reached. Now the implementation just writes the stream and always adds a 0 value. There is no check if the streamlength is already even or not. Maybe constantly adding the 0 value causes that?

**Review by gofal — APPROVED** [review]

**Comment by amoerie** [comment]
> My assumption: there was this method in EvenLengthBuffer, that previously wrote the stream and filled with 0-values until the desired length is reached. Now the implementation just writes the stream and always adds a 0 value. There is no check if the streamlength is already even or not. Maybe constantly adding the 0 value causes that?

No @gofal this PR only fixes an issue in StreamByteBuffer, the code in EvenLengthBuffer was not modified and it still has the original code.

I will add a comment on the other PR that *does* modify EvenLengthBuffer and address your concerns there.

**Comment by amoerie** [comment]
@gofal Can this be merged?

**Comment by gofal** [comment]
please give me a minute to review. thanks

**Comment by gofal** [comment]
so. i am done.

**Comment by amoerie** [comment]
> please give me a minute to review. thanks

No problem, it was just confusing to me that you approved the changes without saying anything or merging it. :-)

**Comment by gofal** [comment]
sure, i will merge it. just wanted to review othe branches, too.
I now fixed the changelog from previous merged PR, resolved the conflicts here, and will merge as soon as the checks all have passed.

**Comment by amoerie** [comment]
Take your time, and thanks for reviewing!

**Pull request merged**
