### PR TITLE
Delete v4 changelog

### PR DESCRIPTION
**Pull request by amoerie**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Remove Changelog.md
- Rename Changelog5.md --> Changelog.md

The v4 code has already been deleted anyway. If we want to make new releases for v4, we would have to do so starting from the 4.0 branch.

### CODE REVIEW

**Review by mrbean-bremen — COMMENTED** [review]
There is another reference in [docfx.json](https://github.com/fo-dicom/fo-dicom/blob/development/Documentation/v5/docfx.json).
And I guess you just renamed `ChangeLog5.md` to `ChangeLog.md`, I didn't check for changes there (the change view here is not really helpful).

**Comment by amoerie** [comment]
> There is another reference in [docfx.json](https://github.com/fo-dicom/fo-dicom/blob/development/Documentation/v5/docfx.json).
> And I guess you just renamed `ChangeLog5.md` to `ChangeLog.md`, I didn't check for changes there (the change view here is not really helpful).

I actually removed the old changelog first, made a git commit, and then renamed changelog5 to changelog, but to git it is all the same.

Thanks for mentioning the docfx file, I'll fix that next time I'm at the computer.

**Comment by amoerie** [comment]
It's also amazing that our CI still randomly fails. 🤦‍♂️ I'll keep removing flaky tests until it is finally predictable...

**Comment by mrbean-bremen** [comment]
> I actually removed the old changelog first, made a git commit, and then renamed changelog5 to changelog, but to git it is all the same.

Actually git should be able to detect the renaming just fine, as it uses the hashes of the file content instead of the file names to track files. It is GitHub that is having trouble here...

**Comment by mrbean-bremen** [comment]
> Thanks for mentioning the docfx file, I'll fix that next time I'm at the computer.

You may have forgotten this 😄

**Comment by amoerie** [comment]
> > Thanks for mentioning the docfx file, I'll fix that next time I'm at the computer.
> 
> You may have forgotten this 😄

Thanks for the reminder 👍 
Doing this now because I won't be able to contribute to fo-dicom for a short while (weeks/months) after today.

Hopefully @gofal will appear again soon, he's been offline for a while now. I could have merged some of the pull requests by now, but it's a little meaningless since @gofal is the only one who can publish new nuget versions, so the actual release of those changes would have to wait for him anyway.

**Comment by mrbean-bremen** [comment]
>  I could have merged some of the pull requests by now, but it's a little meaningless since @gofal is the only one who can publish new nuget versions, so the actual release of those changes would have to wait for him anyway.

Yes, I think it makes sense to have a second person (someone who is actively contributing, meaning you in this case of course) to be able to do this. In the other projects I'm contributing to there is always at least a second person to be able to make a release. There are always circumstances where a person is not able to contribute for some time, so a backup is helpful.

**Review by mrbean-bremen — APPROVED** [review]

**Comment by mrbean-bremen** [comment]
>  I won't be able to contribute to fo-dicom for a short while (weeks/months) after today.

Wish you all the best for whatever you have to do in that time...

**Comment by amoerie** [comment]
> Wish you all the best for whatever you have to do in that time...

Thanks, it's nothing negative. My second child is about to be born. 🙂 So open source will have to take a step back for a little while until the dust settles.

**Comment by mrbean-bremen** [comment]
> My second child is about to be born

Ah, congratulations in this case! Have a nice time!

**Comment by gofal** [comment]
Congratulations!
Sorry for being away for so long, there is no excuse for that.

But merging PRs is always a good idea if they where accepted by you. Because then future branches are closer together will have less merge conflicts, just as it now with this PR, every single other PR has unresolvable conflicts.
publishing on nuget on a complete different thing. I will give you rights there, of course.

**Comment by amoerie** [comment]
> Congratulations! 

Thanks! 

> Sorry for being away for so long, there is no excuse for that.

Apology not accepted, you can be away as long as you want :-) Nobody is paying you to be here..
But like @mrbean-bremen said, it would be nice to have a backup person for the release deployments so fo-dicom is not stuck when you are absent.

> But merging PRs is always a good idea if they where accepted by you. Because then future branches are closer together will have less merge conflicts, just as it now with this PR, every single other PR has unresolvable conflicts. publishing on nuget on a complete different thing. I will give you rights there, of course.

Good point, I''ll keep that in mind in the future.

**Pull request merged**
