### PR TITLE
Update dictionary to version 2015b. Connects to #9

### PR DESCRIPTION
**Pull request by anders9ustafsson**
Partially inspired by @rickardraysearch (reading tags and UIDs from the DICOM XML documents), I have now created T4 templates to do exactly that. When running the code generator for each respective file (*Dictionaries/DICOM Dictionary.tt*, *DicomTagGenerated.tt* and *DicomUIDGenerated.tt*), the generator fetches the latest version of the XML files and transforms the relevant data to DICOM tags and UIDs.

As long as the structure of the DICOM XML documents do not substantially change, these templates can be re-run every time NEMA publishes a new version of the DICOM standard.

Running the code generator may take a while, since fetching the XML files can be time consuming. However, as far as I know code generation will not run automatically as long as the *.tt* file is not modified. So, if all works as intended you will normally not notice the presence of the T4 templates when working with the DICOM solution :-)

I have not yet been able to automatically update the *.gz* compressed file, so currently this file has to be re-created manually every time *DICOM Dictionary.xml* has been updated.

As a consequence of updating the dictionary, I also had to introduce 3 new value representations, *UC*, *UR* and *OD*. Please take an extra look at how these fields have been defined in the *DicomVR.cs* file, in case I have interpreted the VR definition incorrectly in some way.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
If this PR is accepted, I will write up instructions on how to update the dictionary, tags and UIDs on the wiki.

**Comment by IanYates** [comment]
I see what you mean about the fetch taking a while.  I froze VS for a while and gave up.
I'm downloading the XML manually and bringing it in to the solution for local exploration and testing.

A quick thought which I'm happy to have slapped down :)
Would it be worthwhile including a copy of the dictionary XML files in the repository?  (assuming the licence permits such inclusion).  I only say this from the point of view of being able to check out the repo and build it completely.  I appreciate that the output of the T4 templates is included and, from a build perspective, that's all that's strictly needed   

Having just finished the download of part16.xml I can see that ~20MB is required for all three files, which is pretty hefty to include in the repo but would be nice from a "point in time" snapshot of how fo-DICOM was built & released.

Also, in my experience you're right about the T4 templates only being invoked if you specifically request their invocation.

If you think it's a good idea to include the XML in the repo, it could be placed into that new T4 subfolder.  Then the options are to
a) Include another T4 that could be executed to download updated XML; or
b) Add a parameter to the GetTags() function which says whether or not the XML files should be download.

**Comment by anders9ustafsson** [comment]
Thanks for looking into this, Ian.

Yes, I realize the downloading will be a bottleneck for people wanting to execute the T4 templates. My rationale for reading from the web location is to ensure that the dictionary is not created from outdated XML files, but from a debugging perspective the current approach is sub-optimal, I agree.

I'll give the options you have listed some more thought, and I will come back with my view in a short while.

**Comment by IanYates** [comment]
No problem.  It's one of those bits of code that seems to just work at the moment so I'm pretty happy overall.  Debugging was tricky but it made sense once I got the XML locally downloaded.  I briefly tried to use HostSpecific=true and then resolve local paths for XML but it got a bit fiddly.

I make extensive use of (heavily modified) TypeLite to get my C# classes available in Typescript/JavaScript.  TypeLite makes use of a T4 to kick off its work to reflect over the current assembly's types, but 95% of its logic is in a separate assembly that's referenced just for the execution of the template.  Debugging is certainly easier and intellisense/ReSharper behave better.  

The Tuple<a,b,c,d> looks intimidating at first but it's a convenient way to smuggle the data around for something that, after all, isn't part of the runtime library.  Once you see what it's holding it's pretty clear.

With all that said, perfect can be the enemy of the good.  The code here certainly works (great job on parsing apart that huge XML!) and reads well enough for me so I'm :+1 for merging this.

**Comment by anders9ustafsson** [comment]
I have updated the T4 template files with improved documentation and code structure, but I still have a few changes left. I'll try to get the last changes in later tonight, including a solution for using local DICOM XML files in debug mode.

**Comment by anders9ustafsson** [comment]
I have now modified the *dictionarymethods.t4* file so that in *debug* mode it reads from local copies of the DICOM Part X XML files.

To configure the *.t4* file to read local XML files, you only need to alter the first line in the file to:

    <#@ template debug="true" hostspecific="true" language="C#" #>

i.e. both `debug` and `hostspecific` attributes should be set to `true`.

In normal configuration, the T4 engine will read from the internet location.

I will of course write up a wiki page describing this workflow in detail.

Thanks again, Ian, for reviewing this PR and for your advice on code generation. @IanYates @hdesouky @GMZ If you have further concerns regarding this PR, do not hesitate to voice them. Otherwise I'll merge this PR within a day.

**Pull request merged**
