### PR TITLE
Rebase version 4

### PR DESCRIPTION
**Pull request by gofal**

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@gofal - is this a rebase of the current version? In this case I don't think we need any review (and it is not really practical given the number of changes), and you could just merge it.

**Comment by gofal** [comment]
yes, this is just the reabase. but github doesn't let me "rebase and merge", because it complains about some conflicts. But there cannot be conflicts, there has not been any change in branch "4.0". 
So i started to read github-docs and did not finish that on friday. Today I continue. To this PR will either be merged within the next hour, or it will be deleted.

**Comment by mrbean-bremen** [comment]
If this doesn't work due to some GitHub limitations, you can just rebase and force-push it from your local repository.

**Comment by gofal** [comment]
Ah, now I got it.
branch "4.0" cannot reabased with development directly. Because branch "master" is the common root, from which "developement", "4.0", "3.0" etc have been branched. So I first had to rebase development into master-branch, and then from that I could rebase 4.0-branch from master.

**Comment by gofal** [comment]
sadly github did not write something like "cannot rebase, because no common root branch" or similar. But it tells about "conflicts", which is technically correct, but not helpful if you have to find a solution.

**Pull request closed without merging**
