### PR TITLE
Fix: Unable to retrieve correct VR when the DICOM element's length is a blank character (e.g., 0x200A) #1847

### PR DESCRIPTION
**Pull request by DMIAOCHEN**
… a blank character (e.g., 0x200A) #1847

- Modified empty string check to specifically handle 0x2020.
- Added unit tests to verify the behavior.

Fixes # .

#### Checklist
- [ ] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]
This leaves still the possibility of 0x2020 being a length, but as this is much less likely than 0xA20, I think it is sufficient.

**Review by mrbean-bremen — CHANGES_REQUESTED** [review]
I was a bit fast approving this: please also add an entry to the release notes, and add yourself to the contributors list.

**Comment by DMIAOCHEN** [comment]
Thanks for the quick approval! I’ve added the entry to the changelog and included myself in the contributors list.

**Review by mrbean-bremen — APPROVED** [review]
Thanks!

**Review by gofal — APPROVED** [review]
Thanks!

**Pull request merged**
