### PR TITLE
close TCP connection on Send(Async) returns, proposing fix for GH-745

### PR DESCRIPTION
**Pull request by mia-san**
Fixes 745# .

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- proposing fix for GH-745, based on the work by @gofal

### CODE REVIEW

**Comment by mia-san** [comment]
while we're testing our product, we sometimes see ObjectDisposedException on releasing association with #780, #793, #797 and #802 applied.
the exception is not always happen(20% to 25% in our case).
protocol doesn't matter (C-FIND, C-MOVE in our case).

stack trace is
```
   System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
```

I sprinkled debug logging, found that WriteAsync is not fully awaited, namely
https://github.com/fo-dicom/fo-dicom/blob/94cd7a884d76750839d69ff1c49e1a63d5cc5a89/DICOM/Network/DicomService.cs#L334
interestingly, Association Release Request is received by SCP and we receives Association Release Response after that.

it seems to me that there's race between sending thread and receiving thread.
probably
1. sending thread calls WriteAsync.
2. sending thread calls BeginWriteAsync internally.
3. AssociationReleaseRequest on the wire.
4. SCP receives AssociationReleaseRequest
5. SCP send AssociationReleaseResponse back.
6. receiving thread received AssociationReleaseResponse.
7. receiving thread disposes NetworkStream.
8. sending thread calls EndWriteAsync internally on disposed NetworkStream, end up to ObjectDisposedException.

it would be better to discard ObjectDisposedException same way as other part of DicomService.

**Comment by gofal** [comment]
Hm, now with this last change CI on AppVeyor reports some errors like: 
System.Net.WebException : Unable to connect to the remote server
---- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 195.220.108.5:443

**Comment by mia-san** [comment]
I don't think the failure is caused by my last change(2c927f41cd8f4ec3549ab1ab079c80d2a43aebda).
as you see, 2c927f41cd8f4ec3549ab1ab079c80d2a43aebda add catch clause for ObjectDisposedException.

also, 195.220.108.5 seems to belong to somewhere in france, and port 443 is https.
DICOM transaction should have nothing to do with https.

actually, some unit tests are trying to download DICOM file from www.creatis.insa-lyon.fr, which in turn resolved to 195.220.108.5.
```
$ host www.creatis.insa-lyon.fr
www.creatis.insa-lyon.fr is an alias for tux.creatis.insa-lyon.fr.
tux.creatis.insa-lyon.fr has address 195.220.108.5
tux.creatis.insa-lyon.fr mail is handled by 10 cisrelais.univ-lyon1.fr.
tux.creatis.insa-lyon.fr mail is handled by 20 cismrelais.univ-lyon1.fr.
```

search solution by "https://, I see
> Tests\Desktop\Bugs\GH526.cs(23):                    @"https://www.creatis.insa-lyon.fr/~jpr/PUBLIC/gdcm/gdcmSampleData/DICOM_MPEG_from_ETIAM/ETIAM_video_002.dcm",
> Tests\Desktop\Media\DicomDirectoryTest.cs(80):                "https://www.creatis.insa-lyon.fr/~jpr/PUBLIC/gdcm/gdcmSampleData/Philips_Medical_Images/mr711-mr712/abd1.zip");

**Comment by gofal** [comment]
Ah, sorry. I should really have investigated more before writing my last post.

So you'd say this pull request is ready for merging?

**Comment by mia-san** [comment]
I'm not convinced, as I don't fully understand how current code works.
also, failing unit tests make me nervous(longer timeout helps?)
but thanks to your testing and out testing team, this pull-request should be mostly safe to get merged.

btw, I'll put 'patched' version of fo-dicom into production, expecting intensive DICOM transaction.
(#780, #793, #797, #802)
I'd like to see how it works at least for a month.

of course, more testing by anyone else is welcome.

**Pull request merged**
