### PR TITLE
Support empty buffer at end of fragment in multiframe DICOM file

### LINKED ISSUE #1586: Rendering a multiframe DICOM file where the last fragment is 0 bytes crashes
**Describe the bug**
Rendering a multiframe DICOM file where the last fragment is 0 bytes crashes

**To Reproduce**
I will provide a unit test

**Expected behavior**
Rendering should ignore the 0 byte fragment.

**Screenshots or test DICOM files**
I will provide a unit test

**Environment**
Fellow Oak DICOM version: latest development
OS: any
Platform: any

A little more details:
The pixel data tag fragment length is 0 in the original DICOM file.  This causes the OffsetTable to remain empty.
Later, the EncapsulatedPixelData.GetFrame method throws an exception that varying fragment lengths are not supported.
However, the only problem is a 0 byte buffer at the very end.
I am still wondering if this a parsing issue or not. 
Unfortunately I cannot share the DICOM file here (yet) because the patient information is visible in the pixel data and I haven't figured out how to anonymize those yet. :-)

### PR DESCRIPTION
**Pull request by amoerie**
Fixes #1586

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Ignore empty buffer at end of fragment

@gofal I actually have a sample DICOM file from a real modality, but there is readable patient data in the pixel data itself. 
The unit test is written against another existing multiframe.dcm, but I then massage the dataset in a way that it resembles the result of my broken DICOM file. I've verified that the original code throws the same exception, and the fix works both for the original file and the unit test. However, as you will understand, I cannot add my DICOM file to this repository without anonymizing it first, and I currently don't have the tools to do so.

I'd be interested if you (or @mrbean-bremen) have any good software to do this.

### CODE REVIEW

**Comment by gofal** [comment]
the issue with anonymizer tools ofen is, that they also sometimes sanitize the file or the issue is not observable afterwards.
What I usually do then, is to use a hex-editor like HxD. There I open the dicom-file as binary and overwrite the bytes, that contain the patients name, with some other bytes. (So patient "John^Doe" becomes "AAAA^BBB"). All the raw data and dicomitem-length and so on stay the same. Some manual work, but a perfect way to anonymize some broken files.

**Comment by amoerie** [comment]
Thanks, and that will work for specific encoding issues indeed, but what if I have a 14 frame multiframe dicom file with patient name and birthdate burned into the pixel data themselves? I basically need to blank out certain regions of the images themselves.

**Comment by mrbean-bremen** [comment]
If you are comfortable with Python, you could try [deid](https://pypi.org/project/deid/).

**Comment by gofal** [comment]
> but what if I have a 14 frame multiframe dicom file with patient name and birthdate burned into the pixel data themselves?

sorry, no solution for such cases.

**Comment by gofal** [comment]
> If you are comfortable with Python, you could try [deid](https://pypi.org/project/deid/).

" We are looking for collaborators to develop and validate an OCR cleaning method!"
If they manage to do so, this tool would be really great!

**Comment by mrbean-bremen** [comment]
> If they manage to do so, this tool would be really great!

Yes, indeed, though for simple purposes (cleaning all pixel data or a rectangular area of the pixel data) the current implementation is good enough.

**Comment by amoerie** [comment]
> > but what if I have a 14 frame multiframe dicom file with patient name and birthdate burned into the pixel data themselves?
> 
> sorry, no solution for such cases.

I looked at the Python solution but since I never use Python and don't even have it installed, I wanted to see if I could adapt my own anonymizer to accommodate my own feature request.
And it worked!

The 2.3.0 release of https://github.com/amoerie/dcmanonymize support passing in a rectangular region via coordinates, and it will make those regions empty (they turn black or white depending on the LUTs). I'm not sure I properly support all of the various possible combinations of photometric interpretations and planar coordinates, but so far my tests have worked. :-)

Example usage:

`dcmanonymize test.dcm --blank-rectangle "(250,250)->(500,500)"`

**Comment by amoerie** [comment]
Now if only there was an easy and good OCR library for .NET :-) ...

**Comment by amoerie** [comment]
So, in the end, I managed to reproduce the problem by artificially creating the same DicomFile structure in C#, by simply creating fragmented pixel data with an empty buffer fragment at the end. This produced the exact same error as the real DicomFile, so now the test confirms that the fix is working.

As usual, DICOM files should not have an empty fragment at the end, but this is another "deal with the real world" kind of fix. :-)

**Review by mrbean-bremen — APPROVED** [review]
Looks good to me!

**Review by gofal — APPROVED** [review]

**Pull request merged**
