### PR TITLE
Updated some NuGet dependencies to .NET 5 preview 3.0

### PR DESCRIPTION
**Pull request by MaherJendoubi**

### CODE REVIEW

**Comment by gofal** [comment]
Not sure: does it break compatibility if the dependencies are .net5? will fo-dicom still work fine on machines that have netframework4.6.2 installed?

**Comment by MaherJendoubi** [comment]
@gofal 
image

**Comment by MaherJendoubi** [comment]
@gofal would you please change these versions?

image

**Comment by MaherJendoubi** [comment]
The TFM of .NET 5 is **net5.0**.

**Comment by gofal** [comment]
That's not clear to me, please help me to understand:
Top priority of fo-dicom is to be runable on as many different environments as possible. Version 4 is Portable (PCL) plus many different builds for various platforms. The new version 5 now will be one assembly in netStandard2.0 (not 2.1, because we would then loose compatibility to netframework).

So when you write "update dependencies to net 5", does that mean, that net5 is required to run fo-dicom (or that net5 runtime dlls have to be shipped with fo-dicom)?

**Comment by MaherJendoubi** [comment]
I apologize for not being enough clear. The .NET 5 is the next version of .NET Core after 3.X.
When I did the update of some package to .NET 5 Preview 3.0, the net5 is required to run fo-dicom likewise with .NET Core 3.X.

**Comment by amoerie** [comment]
I am against this PR. 

1. .NET 5 is not even released yet. fo-dicom should strive to be a very stable, reliable library, not one that chases the newest preview packages.

2. .NET 5 would break compatibility with .NET framework. Any .NET framework consumers would be left in the cold.

**Pull request closed without merging**
