### PR TITLE
Adds an event handler to DicomClient and allows a user to inspect or …

### PR DESCRIPTION
**Pull request by Siyam**
…update a DicomClientRequest Association prior to it being sent.

see #1048

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Adds the ability to attach an event handler to DicomClient to get the outgoing association request.  This event follows the same design/pattern as other events in the Dicom Client Class
- This offers better flexibility for developers who may need to make slight adjustments or changes to presentation contexts / transfer syntaxes.

### CODE REVIEW

**Comment by amoerie** [comment]
Let's talk about this PR, because it's been open for 2 weeks now and nobody has replied to you yet. For that, I apologize.

Could you explain the use case you have for needing this feature?
As far as I know, there is already "AdditionalPresentationContexts" and "AdditionalExtendedNegotiations" on DicomClient which allows for manipulating the association request. Furthermore, the association request will be derived from the queued DICOM requests you added before you call SendAsync().

In the future, may I suggest that you first open an issue to discuss any problems you have.
Then, after discussing possible pros and cons and chalking out a solution, you can create a PR.

I'm not saying that this way of doing things is obligatory here on Github, but I think you'll find the results more satisfactory.  😉

**Comment by Siyam** [comment]
Hi @amoerie this was to address  #1048 because the current implementation had some limitations based on how certain DICOM SCP's were interpreting presentation contexts.  This event allows a user to have a bit more control on the association request before it gets sent to deal with any kind of nuances with the SCP.

**Comment by amoerie** [comment]
I've needed some time to put my finger on it, but the thing I slightly dislike about this PR is that it breaks the "style" of the other event handlers. The other event handlers are more of a "notification" that something happened: AssociationAccepted, AssociationReleased, StateChanged. There is nothing you can do about it anymore, but DicomClient lets you subscribe to these events.

In your new "AssociationRequest" event handler, you expose the DicomAssociation before we send it. The handler that follows the same style of the others would be "AssociationRequested", but then of course that implies it would only trigger after sending the DicomAssociation request, at which point it is obviously too late to manipulate it.

I've yet to come up with a better idea though, but perhaps we can take inspiration from prior art. For example, the HttpClient class in the .NET base class library is also rather easy to use, but very flexible to customize, by using a custom MessageHandler that is passable to the HttpClient constructor. It then gets the opportunity to modify any outgoing requests or incoming responses. 

I believe that would be a good, generic, flexible system that will suit everyone's use case. What do you think about this @Siyam ? I am also eager  to hear @gofal 's thoughts on this. 😉

**Comment by gofal** [comment]
This idea reminds me on the Asp.net Middleware concept, where a (experienced) developer can inject and manipulate/log/suppress every incomming and outgoing message. That would be really very generic.
Would that also solve other problems? like issue #1036?

If it is just because of issue #1048 then I think this would be shooting with cannons on sparrows (thats a germain saying, not sure if it also exists in english). i am currently trying to implement the same way as dcmtk does, by creating a separate presentation context for the transfersyntax of the original file. This would have the advantage, that it would also be an enhancement for "normal" users under the hood.

But if such a DicomMessageHandler also solves other problems, then it sure would be worth the effort.

**Comment by amoerie** [comment]
I absolute love the expression "shooting sparrows with cannons"! 😁

It's very reasonable to say that that solution is a little overkill just for this problem, but I do think that if we went digging, we could find a lot of use cases for such a middleware. 

However, I don't think one solution excludes the other: your suggested improvement would still be valid and, I think, a worthwhile effort, regardless of whether we implement this middleware at all.

**Comment by Siyam** [comment]
Sure @amoerie , @gofal , many of these proposed solutions would be beneficial.  I created this PR and issue mainly because I though it would highlight an important use case/need for developers trying to use the library to suit a wide variety of different implementations.  The middleware pipeline is a great idea too giving users much flexibility (however it could be also a little more challenging to implement).

**Comment by gofal** [comment]
I implemented the strategy of sending a separate PresentationContext for the original TS in version 5.
Code changes are rather small, I tested a lot and it seems to be a simple change. I could implement it in version 4, too. No big change. Or do you want to check out version 5?

**Comment by gofal** [comment]
Anyway, is it fine for you, to reject this pullrequest, after there is now an other solution for your problem?

**Pull request closed without merging**
