### PR TITLE
Add dependabot.yml 

### PR DESCRIPTION
**Pull request by amoerie**
Github has an automated bot called "dependabot" that can scan your nuget dependencies and automatically create pull requests to update them. It's quite user friendly and might help us stay up to date with things like xunit and other dependencies.

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Add dependabot.yml
- Dependabot will scan the fo-dicom repository monthly and automatically open a pull request for each outdated nuget dependency

Read more here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

### CODE REVIEW

**Review by mrbean-bremen — APPROVED** [review]
I think this is a good idea. We may still chose to reject an update.

**Review by gofal — APPROVED** [review]

**Comment by mrbean-bremen** [comment]
Out of interest: how all these PRs shall be handled now? There are some (minor patch updates, or the update of fo-dicom.Codecs), that probably can be merged right away. There are some PRs, that have dependencies to other ones and therefore are failing, that need to be merged in a certain order, if at all. Are there some updates that we don't want to have? May there be compatibility issues?

**Comment by gofal** [comment]
Those were also my thoughts. Was surprised about the amout of PRs that popped up, and I also was not aware about the consequences and the conflicts. it seems, some packages have to be updated together and checked.
Now I also start to be secptical, if these full automatic PRs are a good idea. 

Or is there a chance to configure, that there should only be 1 monthy PR suggesting some version updates?

**Comment by mrbean-bremen** [comment]
As far as I understand, the packages can be [configured in the config file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates). I also think that this is just the initial surge of updates - ones there are done (or disabled), there won't be many afterwards. I use similar bots for Python packages.
Anyway, this looks to me that we have to decide that on a one-by-one base, probably by just approving, and merging if nobody objects as any other PR.

**Comment by mrbean-bremen** [comment]
There are options to [ignore some updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore), or to explicitely allow only certain updates. The update frequency and the maximum number of PRs can also be configured.

**Pull request merged**
