### PR TITLE
Update to DICOM Standard 2020b.

### PR DESCRIPTION
**Pull request by anders9ustafsson**
#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Update DICOM dictionary, including tags UIDs and anonymizer profiles, to latest release of DICOM standard 2020b.

### CODE REVIEW

**Comment by amoerie** [comment]
Hi Anders, thanks for the PR!

The changes look good to me, I am assuming most of it is generated anyway. I do have a question though: is it documented somewhere how you go through this process? It might be interesting to write that down for future reference, if ever there comes a time when you can't do this anymore. 

If it already is documented, forgive me please.

**Comment by anders9ustafsson** [comment]
>  is it documented somewhere how you go through this process?

As I also asked Reinhard when we texted the other day; have you read the [wiki](https://github.com/fo-dicom/fo-dicom/wiki/DICOM-dictionary-generation)? 😃

**Comment by amoerie** [comment]
You are a legend, thanks for writing this stuff down! I was on mobile and therefore not in the best position to go look for it, but that's just a bad excuse of course. 🙂

**Comment by anders9ustafsson** [comment]
Incidentally, the instructions for adding a new VR are also on the [wiki](https://github.com/fo-dicom/fo-dicom/wiki/Implementing-new-Value-Representation). 😃

**Pull request merged**
