### PR TITLE
Move to .NET Standard

### PR DESCRIPTION
**Pull request by amoerie**
I am opening this pull request early (this branch is still very much a work in progress) so our progress can be more transparent to the community. The purpose of this PR is to prepare for a new major release, 5.0. In this release, we intend to move the codebase to .NET Standard, remove support for Portable Class libraries and remove any APIs that have been obsolete for a while now.

This should let us simplify the code base in many ways and pave the way for many long requested features that were being held back by technological constraints, such as support for TLS.

Furthermore, we intend to recognize the great work done by our friends at [Efferent](https://github.com/Efferent-Health) who have created amazing, cross-platform C++ codecs that trump the existing ones in many ways. We will completely drop the existing codecs and push their implementation forward as the official way to do image transcoding using Fellow Oak DICOM. 

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- [x] Move all projects to .NET Standard 2.0
- [ ] Use Microsoft's Dependency Injection container to register and instantiate fo-dicom services instead of using static methods and Activator.CreateInstance.
- [x] Consolidate test projects to one project with multiple target frameworks
- [x] Remove obsolete APIs (old DicomClient, etc.)
- [ ] Move to Efferent codecs (See https://github.com/Efferent-Health/fo-dicom.Codecs/issues/6 )
- [ ] Add [ImageSharp](https://github.com/SixLabors/ImageSharp) support and use it by default
- [ ] Move continuous integration away from AppVeyor (currently looking into Github Actions)
- [ ] Add support for TLS #688 
- [x] Clean up compiler conditionals
- [ ] Remove IFileReference
- [ ] Use native C# types instead of byte arrays in DicomElements

### CODE REVIEW

**Comment by amoerie** [comment]
At this point, building fo-dicom in GIthub Actions works, it's just the tests that are still failing. Now, I know that tests fail even on my development machine, but some tests seem to be related to files not being found, presumably because of linux and macOS being case sensitive. So I'll have to go through the errors and see what's going on there, but that's for another day!

**Comment by amoerie** [comment]
Looks like most of the "file not found" tests are gone now. We should get the tests stable as soon as possible in my opinion, because until then every refactoring is quite dangerous.

**Comment by gofal** [comment]
> Looks like most of the "file not found" tests are gone now. We should get the tests stable as soon as possible in my opinion, because until then every refactoring is quite dangerous.

Agree. On my development machine it is a constant number of tests that is always failing. All of them fail because of DicomCodecException. the samle data used cannot be decoded/encoded. So they will fail as long as we do not have Efferents dicom-codecs integrated.

Alternatively we skip these tests for a while and hopefully do not forget to reactivate them again :-)

**Comment by amoerie** [comment]
In that case I would propose to:

1. Temporarily disable the codecs related tests
2. Fix all other tests
3. Integrate the efferent codecs and re enable the tests

This seems like the fastest path to get back to a full suite of green tests.

**Comment by amoerie** [comment]
I think we might have to delay the integration of ImageSharp until they implement strong naming for their assemblies. Trying to load an assembly that is not strong named causes errors. See https://github.com/SixLabors/ImageSharp/issues/738

It looks like this feature is slated for release somewhere in March.

**Comment by amoerie** [comment]
Update: codec related tests are disabled. ImageSharp related tests are disabled when running on .NET Framework. 

I think the remaining failing tests have to be fixed. They seem to be mostly involve the DicomDataSet validation story. You know more about this than I do @gofal, could you take a look please? I'm not sure where to begin searching.

**Comment by gofal** [comment]
> Dependency injection is supposed to solve isolation issues, not cause them, so I think we're doing something wrong here if you have to disable test parallelization, no?

DI is supposed to avoid reference to concrete implementation, but instead only references interfaces. the DI container then creates the concrete instances.

the issue here is: while in reallive application you setup your DI container once and then run you application, in unittest we want to test many various combinations of DI container setups. Some methods expect WinformsImageManager to be registered others expect ImageShartImagemanger to be registered etc.
Microsofts DI container does not support registering different implementations for the same interface and then returning the desired implementation depending on Thread or Scope,..

So I have not seen an other way than to run the test collections one after the other.

**Comment by amoerie** [comment]
I think the main problem that's causing our tests to hinder each other is the amount of static fields we are currently keeping. We might have to considerably reduce the amount of static managers and other state we're keeping (lazily loaded or not). I'll muck around with this and see if this can be improved.

**Comment by amoerie** [comment]
I've temporarily disabled the unit tests on Ubuntu and macOS to filter out the platform specific problems that still remain. Looks like we have 14 tests that are genuine problems on Windows too. Investigation continues...

**Pull request merged**
