### PR TITLE
Rewrite SOP class extended negotiation support

### LINKED ISSUE #740: Extended DICOM association: fuzzy matching
Hello all!

I am currently trying to send a C-Find request to a PACS, enabling the fuzzy matching for patient names etc.

Searching the code base and the wiki, I only found references to the ExtendedNegotiatons property of the DicomAssociation class and the RootQueryRetrieveInfoFind class with its FuzzySemanticMatching property.

But so far I have not figured out how to actually request that at the association.
See: http://dicom.nema.org/Dicom/2013/output/chtml/part04/sect_C.5.html#table_C.5-1

How can I achieve fuzzy matching for strings?

Thanks in advance!
Harald

### LINKED ISSUE #900: Requested extended negotiation items are accepted by default
### Expected behavior
Requested extended negotiation items should never be returned in the association response unless it is explicitly accepted by the fo-dicom SCP implementation.

See DICOM Standard: ["If the SOP Class Extended Negotiation items do not exist in the A-ASSOCIATE indication they shall be omitted in the A-ASSOCIATE response"](http://dicom.nema.org/medical/dicom/current/output/html/part07.html#sect_D.3.3.5)

### Actual behavior
By default requested extended negotiations are returned in the association-accept response which implies that the SCP supports every extended negotiation item that the SCU has requested for in the association indication.

This could lead to unexpected behavior if the SCU for example sends an indication for relational query and the fo-dicom SCP implementation only supports the default hierarchical search, but because it doesn't handle any extended negotiation it will still unknowingly return an accept for the relational search.

### Steps to reproduce the behavior
Open an association with extended negotiation items provided with any fo-dicom SCP implementation.

### fo-dicom version and OS/platform
fo-dicom 4.0.1
.Net Framework 4.8

### PR DESCRIPTION
**Pull request by davidsybren**
Fixes #900 
Fixes #740 

This PR contains a rewrite of the SOP Class Extended Negotiation support, introducing common extended negotiation and the possibility to add extended negotiation through DicomRequest and the new DicomClient. 

#### Remaining to-do/questions for this PR:
- To-do: Improve unit-test coverage
- Question: Should the old DicomClient be changed to include extended negotiation support?

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Adding full support for SOP class extended negotiation.
- Adding support for SOP class **common** extended negotiation.
- Adding convenient classes for C-Find, C-Get, C-Move and C-Store with the possibility to inject custom convenient classes and support for private and future SOP classes. 
- Adding possibility to indicate extended negotiation items as SCU using DicomRequest and the new DicomClient. (When using DicomRequest you have to take into account that it will affect all request with the same SOP class within one association. The extended negotiation that is set to the last request will be used)
- As an SCP it will be required to explicitly accept the extended negotiation requested by the SCU (just like the presentation contexts). It will be omitted from the AAssociateAC if it is not accepted (according to the DICOM standard).
- Breaking current implementations because of the new DicomExtendedNegotiation and removal of the SubItem classes.

### CODE REVIEW

**Comment by amoerie** [comment]
> Question: Should the old DicomClient be changed to include extended negotiation support?

For me personally, the answer is no. The old DicomClient should be removed in the next major/minor release (obviously not in 4.0.3), so adding new features to it now seems redundant, unless you believe that the required effort is really, really minimal. 
If you do, don't forget to have unit tests for both the old and the new DicomClient.

I currently have a PR open that introduces request timeout detection, and I've only implemented it in the new DicomClient, because the effort to add it to the old DicomClient would be significant, and I've already spent way too much time getting the old DicomClient in the stable state that it is today. This means I'm very hesitant to start fiddling around with its internals again. 

Furthermore, I don't think it matters if extended negotiation support / request timeouts are added to 4.0.3, I think it's perfectly fine to have a newer DicomClient with more capabilities than the old one. The most important aspect of a release is not breaking any existing consumer code. If they want to use new features, they have to touch the code anyway, so they might as well switch over to the new DicomClient, which is 90% API compatible. (the synchronous methods are gone, and some dangerous utility APIs are gone too, such as WaitForAssociation)

**Comment by davidsybren** [comment]
Personally I also don't think that it is needed for the old client, since extended negotiation is new functionality from the client side anyway. It was probably a different story when there was already support for it in the old client.

I haven't really looked at the effort needed to get it implemented in the old client, but I guess we'll leave it out then, unless someone else has good arguments.

**Comment by amoerie** [comment]
Ehm.. was this ready yet?

**Comment by gofal** [comment]
I saw from the comments that the last things to do was creating enum-parameter, and that was done. I looked throught the code and agree to you that it looks very good. Unittests and my own tests ran fine. The Pull request was not marked as WIP. So I merged.

If there is something not complete, then I will revert. If there is something additional missing, please create a new pull request and mark it as WIP.

**Comment by gofal** [comment]
And of course feel free to reopen this issue.

**Comment by davidsybren** [comment]
Yes, I still had to add some tests. But I can create a separate PR for that!

**Comment by gofal** [comment]
thanks!

**Pull request merged**
