### PR TITLE
Dicom.Native for Linux

### PR DESCRIPTION
**Pull request by jaime-olivares**
This PR is the initial attempt to create a Dicom.Native library for Linux and macOS. Please read the README file inside /Dicom.Native.Linux for more details.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@jaime-olivares @AdamLunaDavila Please note that as part of a larger restructuring [project](https://github.com/fo-dicom/fo-dicom/projects/3), the C/C++ codec files and projects are from now on located in the *Native* folder instead of *DICOM.Native*. I realize that this is an inconvenience for you when trying to keep up to speed with the *fo-dicom* development, but I hope you will be able to relatively easily get in sync with the new structures.

**Comment by anders9ustafsson** [comment]
@jaime-olivares @AdamLunaDavila What is the status of this PR? Have you been in contact with user @sieempi about [his work](https://gitter.im/fo-dicom/fo-dicom?at=59301afcfcbbe1891c67e712) on native codecs for .NET Core?

**Comment by anders9ustafsson** [comment]
@jaime-olivares @AdamLunaDavila For the time being, I am closing this PR. If you want to pull this new functionality later on, I would recommend that you first synchronize with the latest commit in the *development* branch, since there might very well be changes related to codecs that are not yet reflected in the code you have pushed here.

**Comment by jaime-olivares** [comment]
This pull-request will  be replaced with a new one for fo-dicom 4.0
Read: https://github.com/fo-dicom/fo-dicom/issues/725

**Pull request closed without merging**
