### PR TITLE
Resolve flickering CI issues (temporary fix, root cause still needs to be investigated)

### LINKED ISSUE #1072: Flickering unit tests cause intermittent CI failures
### Expected behavior
CI stays consistently green when run repeatedly.

### Actual behavior
CI intermittently shows red unit tests

See https://github.com/fo-dicom/fo-dicom/pull/1082/checks?check_run_id=970629876

> The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)
> The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
> FellowOakDicom.Tests.Imaging.Codec.DicomCodecExtensionsTest.EncodeDecodeRLE16

See https://github.com/fo-dicom/fo-dicom/pull/1095/checks?check_run_id=1020792784

> The active test run was aborted. Reason: Test host process crashed
> 
> The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
> FellowOakDicom.Tests.Bugs.GH549.DicomDatasetClone_ToCompressedCodecInParallel_NoMultithreadIssues

### Steps to reproduce the behavior
Repeatedly trigger the CI builds

### fo-dicom version and OS/platform
Latest

### PR DESCRIPTION
**Pull request by amoerie**
Fixes #1072 Root cause related to efferent codecs still needs investigation, but at least this should bring our CI to a perma-green status again.

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] ~~I have updated API documentation~~
- [ ] ~~I have included unit tests~~
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Always install .NET Core 3.1 even when we need to build for .NET Core 2.1. .NET Core 2.1 crashes when it sees a target framework it does not understand. Sometimes this works accidentally. See https://github.com/fo-dicom/fo-dicom/pull/1098/checks?check_run_id=1028124443 for a failed build
- Disable certain codec tests in .NET core that previously have crashed the test host process
-

### CODE REVIEW

**Comment by amoerie** [comment]
Some notes for @gofal (and whomever is reading this)

- I disabled a few unit tests that caused the test host process to crash. This seems to be related to the Efferent codecs, as these tests were quite stable before. They are also stable in the v4 branch where we still use our own codecs.
- I added more tests to the "Imaging" collection, because we seem to still have a thread safety issue somewhere when using the RawImageManager. See https://github.com/fo-dicom/fo-dicom/runs/1036544357. I know, I am avoiding this issue by removing the multithreadedness. 
- There were about 9 tests failing in Dicom.NetCore that were actual issues:
  - DesktopNetworkStream did not work for IPv6. This has been fixed. See https://github.com/fo-dicom/fo-dicom/pull/1101/commits/29b066e19ab16b47324b2223cca8d87eb0e8121e
  - .NET Core throws a subclass of SocketException when the socket fails. The unit test has been changed from Assert.IsType to Assert.IsAssignableFrom
  - Two of the tests verified that pixel data is removed when sending a file where there is no decoder. Because the test file is JPEG Lossless and we *do* have a decoder for that now in .NET Core, this test started failing. See https://github.com/fo-dicom/fo-dicom/pull/1101/commits/f29100cdf1f510c48f63edd3e6019d2af9f7bdde. I've disabled these tests until we come up with a new scenario. Related issue: #538 
- Some test files were missing in the Dicom.NetCore project. See https://github.com/fo-dicom/fo-dicom/pull/1101/commits/51d762d7f7324155f1692afe5461b0ac814c5ae6

So, the remaining work seems to be:
- Re-enable and fix the broken multithreading tests. I've created an issue here to followup with Efferent: https://github.com/fo-dicom/fo-dicom/issues/1100. It's still not 100% clear if the issue is in the codecs or in fo-dicom code.
- Find a new unsupported transfer syntax sample file in .NET Core and re-enable the tests in GH538.cs
- Investigate if we have a separate thread safety problem in our image tests, possibly related to point number 1. See https://github.com/fo-dicom/fo-dicom/runs/1036544357 for a null reference exception that occurs when we call RenderImage in parallel.

**Comment by amoerie** [comment]
@anders9ustafsson @gofal Is there any chance you guys could disable AppVeyor? It only runs the v4-net-framework tests, is terribly slow and its logging output is a lot worse than Github Actions it would seem. I think one of the tests that is now failing is because the CI machine is under very heavy load (this test usually never fails)...

**Comment by amoerie** [comment]
The last three builds have all been completely green. I would suggest we disable flickering tests in the future, because tests that are only 80% of the time green are worthless anyway.

The biggest challenge here is time based tests, mostly related to the DicomClient lingering behavior, and the DicomService timeout behavior. 

The only robust solution to test this would be some sort of virtual time, which already exists in ReactiveX, but some sort of scheduler abstraction would mean another breaking change in DicomService, purely for the purpose of testing, so I would refrain from doing this for now. There are bigger fish to fry.

**Review by gofal — APPROVED** [review]

**Comment by gofal** [comment]
> @anders9ustafsson @gofal Is there any chance you guys could disable AppVeyor? It only runs the v4-net-framework tests, is terribly slow and its logging output is a lot worse than Github Actions it would seem. I think one of the tests that is now failing is because the CI machine is under very heavy load (this test usually never fails)...

Ja sure, I will do.

**Pull request merged**
